[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "268b0a048afcea31e209b91122c4b9e7ec5e7918"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2cf103bfbf60fe3166595a230bf248b5e6d2f8b85c8698711690301aac6e82b3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "b981872a5f0704987866328070ded34db492028e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ed4e1f7fd5d13f1b67a40b33fa72e1528544dcb32a84058c01f4d4bd423b4c2c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "a451b5a6605fa533e47c1eef5f74b362563c1828"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e1968ad4b5c9cbb49f8c06fc4f3843a1445a8e8d0fb0e0a5a48f515c9d7e0a32"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "7eda6daa88c8a1ae538cddeae19b035decca3c53"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5dcdc2349344da3266ac49bfaa1bd6a4887fe151afc3a631cfaaf90e5546d8da"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "0ad09dc61edba1788d28435142d63ec5541f326c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "215cd627ceaba34573b2e14b37eb1e08ca4b305791bbeca4b82dd4268be47dff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e39d59ca1e4b14edd3edbce53eb8d887c0bf410e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7f2673c6b0d6214a85372952ee48d93cc16b4363c52f4a857c684d573af9e013"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "73d5aa24147231b192eaaa18360ec2a89f3687ea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c3efe1086bce15d66befae2af0687f733249d52906daef154bebcd767b550387"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "680e3dbd00967b4a402c194c471cb303f80265a5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "a3392352f000948623802017d936be3771eddf515727cf52be73216031b05250"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "125107f2facd53ee361194df60cfe05ed9a759af"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1448298cced37b1edfae82d896ba31806e5f6e8bffd7bae1b057656754d51b24"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9894c5b62d6c732425db071524d0fd0307f017cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5dfeda18dd168f73c7e16048dcec29834b328b38d5ae70e4750c4758bd8efb9d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b3906c4fbc7fa6a4ba5835bfd95d9d9c969a8118"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b97c03b059c4f8088c0642df86a58b1d1d3b46e1047be76ef866cb2472238388"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b0ea710fb3df5b1b624a629b3dec3650d2fccff7"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "633c5b5a6a43446140f54db9c5ad96b1080bae4ca807a3b3915c9f7c55420599"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "9f43db261684ff7bc8943b83daa11cc9e1261265"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6bc6f5ade396d3da420fadcfa73d32b5173926e497b9b2705055e0ba958d650e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "de392c60916ab49d36f30e2f144c3bdb954ac84e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dc0e32e0c7c2ce6eb19520f74b1e65a9491f33995895b609e39156f7360a92c6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "f92819dd3c6c2148c9ffd3cc7de0a8d6f2f51cb0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "01a95a427a0c00f4eceacd52b77df0f2905a37089ce1c7fa3a9561d7e5353b47"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e25e71ab2deb0302d0c4bc324fd85106c4ec23b0"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0357c184d2b805951dcbe6150cb025b5d112074e3e94ef5b3125f8396a5d821c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "33cdbe0a799e6621e2cbdb1a27737dbdf667e890"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ba8dfc19a797d3afbbcbbb23dbc4d754263ced5fe3bc20cc908ae480a4be8c09"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "3ca039d2cd493ebffe9bb4e6d14bd122075ef5a9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "645ef10c915528734674c5ce95397229b2f46dec6386afa7b10b7e71a04b281f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c5fc2e2e6fcf36e7ab05ecd535250a6227fd2ecf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f4258abf7667a28f51d7427841cfb57b5bdb82b5ff9e28847d570bececc2f2d4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cbbdb622b98d8a2cb4de97a382264b465cb5fd4f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "9913e3b62118099d20502ff9a196553a5ac0656d4681991640d7f8a8cea3719c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3934f813b76710d366e14640e582edfc0dd106bc"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "3778d646cc38532c2b9d9ab522befe11124ae3e064c5e3754c95dc2f17cfa759"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "953c726338b5f886ac1b3567df863ed4fac57bf2"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "3b1655fbdfa4cbdbce48062863f841746dacd2cb224b499d8418c3159256e0f8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b0d1114b00cf6ed5cd6ec79582f29167fa94a46e"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "aa6db1d680315e929bf4dd61367099aed3c48892c295f60c2048f54bae4a427c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bafbd7c956961d3a9773dda708ad834a81937e7e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bc07df84344e3e1291de733c684ecbb78620d2cd36cbf6b6ef6be635b658e829"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8ee11c053272871391760f6808ee1ebdf36cf2ad"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6902720413e95227d2c5eab1ae53055473ddd5a0511caef75591ac82a87cc7d6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "a001d402cf8d021afe659b41352570dc44b27bae"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0521381086095ba3b10e84988890e399c10a21e58a7b1d0694b0760883edc3e5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1ebec8946bb5e4f3ee9ade2a75eb395a0bddad55"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d345588bda24799566cbc8cdf1fcafbb5974a0e67afde062e749fa5f9b47f878"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "117ba670eefbfa4bdd86bff6fac61f14c469c309"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "ae8d2fc8bdef0456f75222cf01ad77ebf99c52e23c20edec55f99703743cf7db"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "7081c7ce6f728acb9ad7e858bd4f44224ec0b2d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ccb3932a4bcabf6afca8bba4ca0ec026bbfa3505a271306b1a13610fadf62786"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3085b6128c9695793692203482c6f44fdbc86d12"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e28fd18cc1a289c33684ea39361d2b604574e99795e106fe7f5cdcaadcd4e81e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "74b537a5063b41c34cd010fd7cd94de11bd4856f"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "7a90d563678ee74a4fc9c2e56088bc2a027b5af120ed4e42a20b5e2ce92535d7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e840f148bc65b5df0017bbed055b6127e8d15faf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ef77015a665b153067012b895b9df1563913817c3e3e581938b954a8cd7ce78e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7684b691841a3691e196abd5e872109ecc255011"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d4df4c4a5f88588af64da59c8a45c20678a44130eb648ddbfc31fbe6fe1de1bd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c5bc394a5c0fa2f93fb07d4ebb046352ef15044a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d6445b11fb7039d156006968cacf745e1bd4ca0fe464fde95efd8a0ee5d7da02"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c9a2021139c239b09bce065c09aaea68d26c5651"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0d81de77b659e7382e0b3a5acf37292c56b31e3b6347960992e849e77f4aa67b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "45381b1b6b3d83f1dcb06f4f28b6f6c12b64ceb7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "16af7e771364ef0f3368e707ebf736e320dbf3192b1af044cb370971d1c27092"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "88511100e7d3ae452cd5fed996ac24cff767f293"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cab2a3606ae10d85a98e583ca46237a10fdace881fe32294d2b542a5abfc0492"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "229dbc63f425f3a6ca902be7c506bd73002bf422"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b96d4e58b0590714838595ca388d6fcc9db3b5fb3d2e3419f4b9620153d5195e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ec85620d860b0f79ee6731d93ebab452c0d0dd46"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "68de30b692aec7bb24f084935c1c5437e4c6a480d4329e262d6acfaa956d6e14"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+1/MUMPS_seq.v4.10.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
