[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ba0afaaadfc64dd9d78fbc4674dbf88cc0b7934c"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "67f6f20686bf92c62d18a0591bd26483263fcc335bb84ebefadf67877a94ad1d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "97ecac230ad49e8ee70c75661ab4eab2df01dbc7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b28b48acc19cea409e1ad16a9abf097b6c7e6ec83ed080037f1c522d99f06680"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "22418abd2c93a32eb24d132f57aaeee40cc906fc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9fe9d5b19c7270f16868b7e5889aa252d856a9365833cf9780cde3fa15a0381a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "f6e055f35fd97abb717831f7671d7b34d1f23642"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5fef79102df8cecb2e2cce99a403159a633d0e76f4dada8c442da401fb5bfd48"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2f52c5f19b0d96c0471fa5dccec86850e379fead"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e9a3b644817683d193b6ebf7966de9a9c4bce5358025587ce4cc6cefc8858f5b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "711325ea4afde65300936f9d6bda0e5a58f2f18e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "361b41c86b155fe97e73375b11b225169ac6006157172381c0805679cd5e969d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0aeb6475a088134df0e29cb8121aa4b42952bf46"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b7973957d3788ba57ee7685c6b7863723c4cb17f9d18b5b50e5d537ab9d7073d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae3192b33809201766f328141b72b7186cd989dc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cf13773e56681b1710d4fdc03275de5f0f935986439a7c7fcb5a5188eae85aa3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c16df8106fd6221ac9e63c1dff6ccaefd25dcc78"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "88217083560d3cb7087c71972585ed99769e95d55f3564a15609abfc7ab75074"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d99a281e7ed6d93974d9b5e18bd441ba7b2d2f4f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8a6b8d0287caa5fd8623a9dc754f32315dbac058d0d8dda3d3fc0f35b9f9de9b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b4cbf9e4a80410edcfeeda9fd280ce8e8c847b55"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2b24aa1942593adcf8acf8f8698990d8a5b3d168ffdf1f71bb93fa3627b8d0ad"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33ede3e3eda9cc262339262455f898a811b4a534"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a680a310c8b4e06afe47dc113abbc84c7684b16e80f17ccfd8e7a9e1e018cec4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42e419e4bfe16a0d0ec722b01f3ebe884ef3b2c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "08beb2773f8ce4a14f1cedd40c989a1d97226835dd30087a8835089dc175f23a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "946900c9a7f0cc1b18b6b1b66a8b3c3f9649638e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "545009cdeb88cc399d8ea8554e0a30b625f3f75bd7ff4748bc09a07f9bb6cd32"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a11c836943a50fa5a7ea03a58ae92e482cca4cbe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e466818529e99d5c26a579cad05ac3c0c9e765ac6bf79501f8b3b416ab85005f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65120926b9471bb3be64c4410e4f764da29b7c0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ed86df681f75bf6fbbb83ed77f47071f314fa889f55832d15136d7542dc59007"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a6e465f10e115d790a4ad3ee40d5fef640685ccc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d9a88b590bd06f42fefab3bc765492f04ce8e2bf875480512d7cb0a43f190164"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79a6ec1d8853d639a57484e379fed560dad12b1f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "54e8f59e716695c5fcf59dfee82d58ddeba7d3bfbb0a4054f674f9e6cc2fd48d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2791789bd20a2d883479e7b672116a041c5ed37"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d4c4bb78121b52ec3f161ea64cb11534bac7ed8a03870a1ee3ab8555fe7dfb2f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "70eac2d6d0e1abeff2121c603947c52d23c64aba"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ee6ef82efb7ba6639a697abd579e04402e9997d29b507d97e2998d2158eeec91"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ba3daf1ebf42fc4825b65b83fea9262c0651429b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "486bf8ecb0ed96d8d06b5f94fb1c5db705cfc9d6870455c9e854b394a816cd72"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e91f8ba10a0bf2fa9ea322f62f2cacdc0f8a4fe0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "232170145469a50fb5d581bca433aaf408c24e27987ed4823f4b6e4cababa5cf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e369d52dee7dafee533ff717bc143fa99d63287c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d26fbaf84627be7e8eb338daab2f7137b597a2d11da9802b040f70f34315d35c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "af3b153fe3b8e8f4cbbda2d1d1ceeca2f8cc10db"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cb07fbd9d8d351df2c8be1bc64ae3c35a3f145dd6f431f02ea4ce2a7d7f7efff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "091ae7951e43d5b0c9fcd0d4732d742700cfbf04"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "61333f8d4855c4538967671a7603c2cedf086259fd8665f3d074f7e035f7d321"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "253fe7deb590694e4d08c17e90cbafd9f24484b7"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "aaafc46a2ead96e677495d93b44bb2613fd70146c9257150f63ff78796e4e34d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1a6fe5eda3bbbe7fb5a940a979a61c1c6d13bc15"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5428f351da09da8427c6926357bcdf1f09640d85d2159637147ac53b46036d29"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3b6e7afc4e83229907100c960141ead557a4dee9"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "2923de2ed768ab5b6cec73ebde3e99f7abc5df850c1f88ffb689a0fe07e434c1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "61e97b5328cf9853088ff491fc57dfc0d66d6f25"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4a5580c1cd36f68e12f7eed966cf94e34b94cd82e5041a13363650e677677cff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "7f8eeb3a3858680713005b87924e096fe594b0d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2c13d3764cfba3a9e2d6362698a79922cf114714877c5d47f440fb088c629bdc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "e9bc6cb81774f270ca419bedb64ecbc741259f2c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "45f7fbb617860b9f3a194d37728d93edc171e053bf0714856466f453e8804ded"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a15bdaae613de4e473ac8855b7221457d01403c8"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "75e6ee5a4f8d0fe03751e9ea0bffe345fb495973fdbd850f34e9637a875deb0e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "095d4f971454793cb0e6fdccbd7a9e6bd1c8e013"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "34788e0ba34ad2b894232c47598f6e651bffdf12d7b73b7cd52bee1e79592e06"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5e82a0644d1952fbb37bae6a0d8e6843e3c9f1d7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "05552a13af26d289c3a74b9e1517a3a3290f5717afa672a29b93e0a76a744993"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "06f00d94b2f134beec0b07099f685a42cfbff199"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d9ebd5ff25cc1cfb2a20364856b41e1ad9cad33f3434681d4fec2b63a2e5fd02"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "86add49b89f0ba568dd4413f8fbbac666a6bd4ea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2d9a4d6de6af51f579a97834a1bb3e0a4c285cfde87b24dba00477b0eee635fe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d88804bd77ac93022ac52e6d23664812ec431590"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1bb68d2e86060916019eb1f96efcf45dd61122f8376774a9edc04e02bb4c1298"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ddd009fd1bebaefe2d96b2904304a65754e737a6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7f2b0e7714140b8d232f42f95bb5d764dcfb7728af95e4be086d38a172143b20"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ef261316656964c4b2b89f5e7690b45b014f3ec4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "88ae9fbd5da5a74babec27f22fc198ac20930d01ac95cb734685ceb1fc6c1372"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4e99300e82ad17b1efb1e9347c68aa09f86e3da6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cb9376dca109c5ffaad6d0246ddd07f9e77f566f32535eed67f313bf9f9b36e4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8f6f3c307398e35be6d81a27dd14e02f94e78407"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "3defaf19b9fa6399a56aab75be77fc1f8768c9a9ab572b8ab9731c366439144b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ef0469a9b676d9f2df905d005392aec393fa4340"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "f0808dcab68f53e9cf8a3ff06fb794fe5f538b7132a3c25c20b64b6e9c6fe539"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "31bc901b52034f8af7294a63ee2323bcb2e9ae59"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "7e02b5f43d6d667b5101abbb9d6956893d22e2f0b8ca4169cbdd672acdcc2f5c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "335ca08fa3ab192e0e574a54530b06d5d34eb8c3"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0a3b4aac648870169625dc1701507e09f48ca0fb73186b5c146aca27c149a970"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2e6aadbd6fc9f307589675f609281d488f18b76d"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ecc4b625a6cbb7f8fcd3964f787e6c36602ea7f56ec6d47d5ebab04d1228ea40"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "88b8b199f4d8ba207c74e377212059711e520a5b"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "87e7022d349fa82c8ea2a93ec1be1fd8a9c12d05fc1a57306c32e765da58f738"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.301+0/MUMPS_seq.v500.700.301.x86_64-w64-mingw32-libgfortran5.tar.gz"
