[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d2b93c1adc99771b92ad32087b92c6e9dba0b0a0"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1052900c6a64ac01fb861ca0d2527ea77f264143eb8c891c250a9f97e97cb95f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ca7c441a95de5bf5e6a2cc5861b480ecaa4d11e8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5ccad41415274b85f7e8bd839476859267b6b995d5314439c7219ed2e6eb4cc2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d4ececb916af27b80ae34951f326ca81ceaa05d5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1fcd02a8975546f37e2a72feb1bf12a35c49420ba5777adb9d77a8fed2bd0b0b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "638a6abe94353de0930f07a1a50540bb9224c412"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1b73580feec8c77185af8cf8f4e0b591a2f7c903f61e9f8fad480019a53212ef"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b15b9c311c2a867e67a771fda97e024a0a97be1f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8811be32a5ec76449a093a711f58f05de6561ba48dbdd6d4f4fac71c303c1ceb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "103431f90fdd413416f2e5f8ca069627dab599be"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "19d6252b8f45508610af3e4812e522725e5bf2ad4c2b10c168be531294a0bb22"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "cf29457e5c0550cf5dc9b49f063cd34efa54a7ee"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9bf212b27c7b53a63574629e2f7590b5c6860447e7ba0d6e7a5b114e362dfd22"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44587013fad9d6c6b84c09286beb121703de5a81"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "84a656f4beb11653cb02afc22eb6d58c4a08e6f1214b8b88fe66cf311f936450"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05021670d7400d00f3d46d21a2585989d2cc0311"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1a4dd4b4fec18133c55a4dd1d3707172cdeab20571dea50b7c8a9c3d8970acf8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a07a23d63cc0beac4025024c7dd47e673af7227a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0f6ec5f324ab5dfa569c2f6416f8b7965d0bb709aa3ae65c4b60f105e0e9cb6d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55e48443a7eaf1f3f40a3877818150accf135050"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f50a698fd7f580d5b118881e91dd3af0fc5b59be957b89e6dfabbd0aa6af69ff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "891e1d11f4a05cfe3156030a80c157694934834d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "814d36d587e04417ec6f442bdf9e9d80b17e4ffd0448a884a27363eef9b31c9c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "625671941cced30017731a9509f34416b2704ee0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "31da59a8d9342303e96c10f82d04a288532d2ce9b1a5c4264752c972add57e0c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56d1826a80ae8b55378cff7a911ca6344b431791"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bee27c5f77a0f7962eab46d4752da6799eb9f33d2c3e5a05c688036e7ad1b3d2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8412b16c128a4e4b4533c8d3acc41c3ee66189ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4d5fea7ba11566ed6cdda36b62bde656bb955ab19dc89a407afd0c1297ee8156"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cb771e148e1743aa991bcfbef13e92f98115ce0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f5c19eb7deda6a30d7a53e230ab445b27184c16688029d3d242225973221a643"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48a93b6d1d499f6fa8411551bb3b17725ba0b6f8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7e7d8be7c4ca2687a21027785c4b0fc3c707bbfa0bf94f93e76d1623337b47e2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "654c624a2bc7772edf04ef1c004d92ca12c88bd7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aabce4ef2e5f658de7dd89f173bfa0b51adba054b5c1772dbf8c43bfa6d026b8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3f9c4144a01669c3e22d44019b68bbebec44482"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "811551e0243bfd86af449149c89f1195349de8ffeccc3fd40f3428a81b165ae3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "26009b57b0444df918d0ad58a1c6f7994a778c96"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6f7f2c3ccdc6ed8c9746d2ad4253d765d37b0d18d4efba3564e8bbc6f7ded2c7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3e522bb78cf4829a90d4c3fbcce86e54a2426e8d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "070f7821088281b326c0fee1851c98574bde1a4a12845981166227fea0a4eba8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "9f9565e4e74807d4c004891c489f2db998fd4124"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "09ca627cb437c9f43557e23bb0f61814861532c29475d9b6958a41a358ee0e39"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4160f71fe03d4b14a015222fc17e9fa38448dd30"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2c912274d6732d8be2a6ac2ced06b467803304b02d912c1e782905ddea7f8c4e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e69175fff0b28a3a45fa754320d64f13ccb5d991"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e54877bebede918d1bec6e0c080685e7104aa90c75479ae131b655f5b6620f92"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "497db8830b01a714d3b4450226f7c6a8de1df472"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2013ae42ad036eccf3e4b720d192242ec1e2ed2b38c7927acc98bc2069d21dff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "695bcf484d0d72d7d6536b7af1daa50ae3c37e14"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "3fa1f65e7c4389f5691b551888d71eb2a974468c14f68544ff2552332ff6190b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e1e514fb8acb93fe91ebd247fb6595562e20694d"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "c3ccf569fcaceb10751ba6b4e8951bf17757dc77f6823f47a713e5c93ab54001"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "428e168e49b2c79f7d378e505150e9f884e3fd66"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0fcd643cc7516ab0f36e84ad6d11196d56eab4ac58a96eae52db31bb1013fd0e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "eb9b0365bc61c4c5eef5c1d1134be348c0b1983b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c61c07b827fc6bc66ec608fc2059a45723df55fdab79598d6bce21079fb249b6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "55c66bdfedf452e72b2d3d50757cbc0110de42e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ae584c08f016eaf4dc503b1c3804aa8016b8bb2f71b9d3a0a1841daa7b634233"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "992fe84f3b3c9ea6d114025a459524b6d1cb59f3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cb8f5f2f13d7326b0a56ff9bd1441f870a424692ddc703ab00e774f6383ff681"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "dc483b77f5ca18bea883fe3cf12fc0a4bc63206c"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "4ad0b551eeb3ad789584e1f06f197054d0d82da2c6033da1744f70a929f52549"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "931006ce43688c84025818904a15c29317bd38f8"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1866168a9b76cfad15da56e55851d9501e5ad84daffaadf66fef38e52994ff71"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bb1a43d94c9819c98813d7734341fc643c1869e3"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "db643d65df7cef9029128ae54d18035907081039a01e6217136d95208d9f64f4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3172e4bf88eee35c6180d114491269ee8646b480"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8440ff9c7b13b49444f93c29e7f29230eca741bdd6f9d6d0c826f99af7cb3862"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8f157f79cb248e0e3c69cadba76c71f3375393e6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2da9320a4b85fca6f45b73d705158a32e4541474440d528b4904dc53cebb114a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "80eff5ca4199d4534d9e033346a5c9d9fcd9cf49"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0fd6729ce9edd69cd76711ea9d7848a18cfd96391d01aaeb7d404cc7f11f37f6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4dcb07388a817652d2889c2edea19c24aad7aa1b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "54cf4ea7d10dbdc253596d5e7a1fda9ae4d9fed281e2adc411dedba577cd5353"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "98e3edd2c3f9378e93d40d4e7cbb897c962b489b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "689edd7cc375d577cfb22b0c2338232263ea8dc0395826ac55635ebe5ff0daa1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a3c27fd20cfc4537879fee56f0d863973c371605"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "231a376e333771ee292ba61baf49de74a9fa1d3c10905e5aa6061fed67337eeb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "21776501ff4a2bd86969a80f5a9fdcc58847122f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "471dab9d3132234a0f6a724276cb30b07a0aecd8ba2bffacce76162799ebc555"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c41a9f1f5fdb48e843313bade016e5ec92e62615"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "efa832a5d757ef8cc4d5e9b548fba61bf5e1c7e67a38d5aac6ade068ae31cb2a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7f8d3f35d7db3932fdb0c19c0eb6ad81b5198e8f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "e6ce38a4308337761810ae0d926819a6634a27656a91a84a36ce583c8328dca4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6d2446f78b1efb6ff3d659213d9bf88d2db1412e"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "202310ece685f4aa6fd8e7c8fd318bbc5d0e8770d2da6c61d08ff6a6ec567051"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "873c1da878968f26b64536f8fddeda2c8b115f37"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "af54d6b01824ea411dfd735105481f5c7e5188d92129e3c1719b68bca214e089"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1eca29acad0154ce979d5560ae8c0c0ca57e6666"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "7c0ca4f68ffcb96a5e6b7f661355922f017eb8ffae5b5992a1bd1eaf26ad97c3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.100+0/MUMPS_seq.v500.600.100.x86_64-w64-mingw32-libgfortran5.tar.gz"
