[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "6749da7fa0825ef3ed2aa4378e52d530e035d36d"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1c34afc1827ab30faa183a238e30c42117d7ecade9914161e64ce30a0565d853"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b6cc3b1cc1171ff0379ac01526874d9fc7d1815e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b52be521c112c090655eeb8f87633c11b94d7b006ec1edf951b6e7a42a2cd3e9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "39854be77a7f1581530931a52080c80ecf1366ad"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d3908c6945a8d6d7399970c40bafa0b76051276345d2d9cca0d135a5ef8b8f11"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e86459f4543d9f7a809913da6a0a4cc66414f33f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8e8555dce1c8e625849e52e5fbf014ed493dcbc1763d58f2b7705954eebe0870"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "9fbe43fc490ec1efdcd33c65c90ce60f4722b309"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0f4014dfd88fd9279904d91d34b02b96a6e99883eba45bef69906db4ad4ecf23"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "a640007c4eb6a7879c829cc073547f01520b955b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c2af1d279b49042976db54dec21caf6e2ac793ce13f30402712e146f16ee2710"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2e2da3d41e41c2bb2cdebb0464e1c1e7da48e851"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "86cdaa805094d0b79a4dd5132aeb20be4b49a895a056fb426686ae089fa3bc9e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "214632e36da3523b8dd28e78a616acf0e74fdf83"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e640488873609eec1d04e33804edb0483f8f5415f174f8a28c6f53d77286f8cb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0534b1ad710e4161b324534938e1961749ba7542"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "006480c3eb50d2c0ff74398178f22890e1e8e1869cdd89bd11c77c63888b3c57"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7276bc843054dbb48a5d99dca4084f85dd6606c5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "296d376397baabf87de64f5b73d33cf37f25d8a282f10e1f037cc2a428f0fbee"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "65721d65af246bc3a22b65c967f1c54c9c87f073"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f7a74f7c567bf3479ba76219936e705fb9dc853135820f73d697ca7e3ce7c560"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc71f7c42c2fc52c12e8cb61b7f286034efccb92"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a8a7cffd44e28248a8e26a51189f4b0ae25f2c655e6ba255884cb5afb3f1d853"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "611a409e2b843da11398cd5ece468979120d0f18"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1ca6758a0161c056df04375be2334034c7c3612dfeb2e5cd04bb263398fa1355"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac8765e9e166732f2eb663d3bd09d0ee5a488f00"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f66d8566f9c1e125cc6bd53cb0781462ac6ca894fb73e81ebe7db95ca20178bc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ada7cea321932eb3c798683c502fbc893623d0b7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "07e3977f1bb1bec02ead135a4a7e574ab6204ff5ad5c6d42f20df86384cf7fa2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a6244bde785c2fadd3ff34ebeadba2d61a827736"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "10b907e5c9d31b75f652b8f656b029558df930db68aeca04848c5503a059702f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c526c1009b496f26bd0d3ba1153e8309b0d24439"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a7340668102f905d7c24540e363cf1d6b92ef7b95db4a8d801ef63c522faf037"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da6a3f5fc91d619605924fcb8ee4bf906069bfaa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "174e2faa92a3d69a6a8d7321cf059f86e9bb94681641e21925c5895da74ab6e9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "537bd020aff5663ea2d4b6e7fe26d578d794ee90"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7037cf40b42d69c8b3afb09c92f40a0871bfb57f9f44b31761d0e973b1b662d2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e0f1cdf2dc43ed8a94c21b04a974ecf419ed3799"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2d2b29c90a8783f194a3a4c498c9960d0a67aef435cc370e7475e2db756c75ef"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ebfc66401d3216c9e9455252f9e33f13ed4906a2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2e683c7eb65a1496bf99b1f06e9fb0b71243670e9ad6f9760d54c706e337be8c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8fba08e5ad79d6ed7a5cfbd157f2113e5a73070a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "372a2a7a9ef651789a79a87d09940f8bb7e9bc9050d0a8bc90fa2fcfbb13471a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a79da2caff1d3f8c26f78af36e1ed4449c92cce3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "746f39fd34392ca0f0d27ced77592b9e30afa635a10683af598e93795977b6a7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "357f0a6cf0da3c23ff52eb6838836ad81a69523f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b6a36a356b4c9ba3fc9bb66f3ba212bb1f69f52cb3dfd284aebdb3b9c00d8373"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a169cdd1737629bfda3d4df9b7ca481139224e96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9b56ae6d2c6a0b088fb7e13a30f1c230d38421da7899b9bd7559400ac0d8e8e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "16cc3540ee9f1416c3a9b5e434cc3b6998ef524a"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "8f4763375920ce6e166ce5458476cc71e95ac13554c5457774d7d4630d4b54cc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ccd21fc6c8871d4201a6fa6bf9516f91d3d7dea9"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "441009ac5874e22117202a65864b27c3463a7777eddff38c75d713e40920a63a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "6eee3200676d6ca8ff555bfce84d391dc9ce964d"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5104acd53270263fa9bcd9d751410403e1b75ea5adc9c8febb7ca9126bcb574f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "58a156959a1e0cb1c2a3474e3a351b24885dca34"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ac80befb1561d5c8d24e3053e1a23ac8063dfda303b1f229ca77e7ae8c7a2012"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "1f80403596f1ef3cbe012d94512f434b0bcedbe0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b9acd1ff85590249e62df6ff79e051124746298c55098d0b137449bd92889f3a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "5a78d24735366b7cdcbfd88b30be62b05d7a037c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f0262650c7e87755805a0ebbc208d10d766c76a7108a8ac806c33be405de4a6f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3d67e4f96e9be0f7b232d722ceda4263973f291b"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "ffb21bf7b79d4f4d214148055ba3f276d7f35a26e0619019e5ae6ef4f07f7899"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c0d113e30aab6e48867c504bd0825f0f35c01c5e"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "2d9e4ae668b79cff6ef102f087fa5fc60209d1f46beef86db9f06f58ea1333d5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "58a05a5c95100671aedb0cf5ae7814140d77d832"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "49eba39f117f08b4845aab6a32dc978d7ab24acdc7b5bcd9acdf94605257dadf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "fc185739f95d4682879a3c76c4c0b9ba51249219"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b19a160d52a3e3c86cd9e2eaca729f8880ded885d33fd07b838f16eff7007a7e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "11c0ddea5d98d61ec9ba22b7c7a4acaf243a9324"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ea17b2c2e91a318c16c57919a7bcb79f774d173fb30d3f96d49d2e22d2215038"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c506bd6e852542f18583d9270b05aa5040d63078"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6c2b2d9d1180d5b41e89b599b7d6209f25257341071c93b13365caa2b21eea1b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2751ddc739d0c9f8b5923d74fe30b1421ca397bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4fa34a44db616bc1d1745676b0f1f25b037c693e91a733872aaa1cf84332fc52"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "efc3ed826824e87fe716cefe90db24d0de9be23d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a939f91038932e99d7c7df6f022edf2c78a1954587fb284c71b16374fc49bc8c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b5d1a3cd83ef3402d7d8c6cfa7806bc014cb17aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "370c16e7da94563c0e3259cf4c371f3175307c920bc9418a66370e9cc5e53ea9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "52994e14193bb1f849283042fead962325e78d54"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "e48e4de8ff891f82ee2eaa22853d9aca16a5c52812a17a2e2947a38fe5f53b28"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5c12c568c8d8b06b759e30826d3d069b58de8e5f"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "d2490b2518ec9d8e4b4d90e1d12a551f0721d056d595c8272bd2a00612174c31"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5e4d7700051e56e11a15f08c2753e06b98a2d5b4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "284e60be04b4b3054b33385b26debb47bd35994a24cba58da11b37f6520587d2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "aff67a5617be234eb31978638b9b1074eb0cf16e"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "27dd3d40bef2ecf818335de692a3244f17f31b2937322c8d568cfe9527d5645a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "685c5434b9289e47f0fe953426c9f8db0c66ed6d"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "15d2cea9d56fc562b10acd21a53ec4e24c5a003d4cd200f9a574ce98dc43e7d7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bb6e535b8143453b166eb7c147b3082b52dd7db6"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "b3fd9f9f7e37b647419f0bf645e44eb6a649fdf1c9aa3b559d015cb4712d138e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.700.300+0/MUMPS_seq.v500.700.300.x86_64-w64-mingw32-libgfortran5.tar.gz"
