[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ce32ae44ff59698eaae28c34eb033cacdd513585"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "4524029968252bd82d73b9c6a25d0253f602e0c84f7f0223008733421622eaa2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "6c7d3665b5de9bf2237f1ccb214e139edd997e1b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "15cbd38b5bf2ddab52176fd3bc292affe887c7a0fb08a2db70556069f547a73a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c44ac265b24b769f9c1fdee991f14df90d29236e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1abd4b1ff573e98d79e98b3eff390876e291105f719cf12c2a7dd9f04cc075ae"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "cb03f580b8627f6e0444a395a79f2c6d0b821825"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4630b68d066491cb22c30d552fb52d35e13c14de451ab16904bb5cb37426b92d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "9588d2d10b663009e84e027e09a21f1e1f7c24ee"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7a4dc4ba714e8885abfe9dfe3f635b8866df66742fb25a1ef4ba76cbf79af3cd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c917964b60d64a770ee0ef772f3abc53e4eebe7e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "09403a591659e2ba05bc44f05aceb7772afa2eb79f1f1073c072a681c8f743e6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b483e65cd45255dc0d0ce3efbe2964baca6382b4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "80d8b631e250cd0c07fe7f683fe4710ab23565210a5dc816eb5f951e40d8e526"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "65d6b9851daff877eaba93995260d5271fa62ac0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c64b6693b8952e2057a3860ba5b3e6551eb14aa474e0e8d76a0bd6840f70561c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6934ba6cab1d34e12d29bab7634eff2867d88ab"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a30b0fe24dba63c7907478fdb3964b88963067bf30926c3ebf078e251f4eeea5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7e41ebc4b89e8552968753cd61a38e63f92f279"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a945ade4445e00c083b4f210995596c48e026d719b305319408cf84740027006"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b82997a78dde12c6176e80e0b0eba6bb3e201e7e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2882454bd6f76feccf2c409791e7d52c6791e74a0976d0a594ee97ffe2d747a5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42382f3fb24187ac54be0774df4cee050d5b5b14"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3d36d7d7db5f3cbf0059bb51db46eba170801537b1325f49eef80e72607269da"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5fb964678621fbbda8ddb641e9a27fbcfbf2a0e6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "644beb1295d02e929d10b5b5a61c90d0d1b0b6258ecc86161707994e4061bf9e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d71f99f94ed718b34e9720585208ba953a28dee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a2451fcd4caa80f194e9e128064e929faab9c416a487a316a9d773364f09fce3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f35549425f1986aab769b296a0642916c6ebfe8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1b58c760ce542d40d3922f2e6a3706d5a6ab53a58fe0ad847d4c5c1e4a5309b3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b1e96744c8fa2a781bbf008543a33290dc3a27b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "555b72a179453d8afb219b610161c4e18327a3954d84d25a735d9885ed815643"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0047bafb44af3e21c0e7c30611c00e4473e927f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "122062cbd08f6e261f0e5b5adc53d5021c7eaf419037a124e88055384ede9f1a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0a2b411fb975234ebc7fbea2e5b26ec2aa991d9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5ed934c390c667196a589842ce6e4dd41e61eb30aafae9cea404c2e9827c70fb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b38e23417508d070aba06931d3dca5fe7994048"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2d4533023b9492e188a32e7674a405dfd746f2cb4b508f5b566123bb92810fec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "668799a57f639f25956351380d087d4d7424b3b5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "999542e5259c2f4467e6e86f9dd5eeb116eb16a6d468b28eb23fe601ef0732a4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1201b90d2975801cacb4f93518deacee142dfd8a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1627f08a41dfd5c8f6cbefa7b23a8ea5a42da837c57872edbdc7e6ea7f36903b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "86754fdbae8dde1016dbeb645e5d7cbaca684a8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8e7621c6109c26027619b4ae97da9e6924db2c8c2318f9e4a36a2072b4dd8173"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4ece7f8162df8ce42fdced08cd168dba618d9784"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1a6d98b39edecdc05e6c1a81b96a351344d3e86b96f6e2b20240075f37265c7c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "2cc91f4feeee08ead09919047e70c8b45728ef5c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9a9a79e81905088e665797a86da2389f5e5edc2d70f8d0697d373db832f167fd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "f35c4d5e67524b61922df3be185e4d13c0174056"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7b0d5f7ae825adb620adcb96d490b95a2efed545166dda62d0c5b809eed6a21e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "cc548f9830c204efce4273701fc49e3dcf7fc41b"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a0145024766544ae6942b8fd9ab66312657f9bb1a1555256961e562cb3455598"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8d110284e0c4064bb4eb41af242f06c8242e1a7f"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ea323072ae17fdaf5ce234b1eb7000037aa49263a21959f2f75d1a59a13525ff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0b261f1088df5b315b27f2ab46a1806226198a95"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "960f5c03cc230451a47e2f8f1332962d924f651950ffd64edf46850c3dbd6bf1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "ba04e4a720f348655d7cecc5b539ff06fa207145"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b83f27599a694594234de3abfd7e32859638ccad3bf2fd78ec3c655a47eac0ef"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "f1d4be14531b4072a32c7d17d2533d36be5fd882"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7633b0974f3c0757a88bf2f3f2923a01c15388b6b642612b5834b296e49f3305"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "d0bbed258d6789ac1d3bfd579c8bcb7a0fc9f8f7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2b5942f19e48adb2ba9e2937fa8b7f540a3e80b0f8e63be99e2d0ae0ba33be93"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6356301d8d6c6f69283a32c8b5cf1f006bc2c41f"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "30fad97e560af022f775c1a4c05786d72aee7d0291210956a1524c30c6397ab0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "71b6790bab0d6f0d24439d0740ad78527248f7c5"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "f804bff3479a55b7637a760986407dbb019c835047c4d9217b36017400aa485e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cac9cd3e5659124413760efd0c0bc7e00522b73c"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "b08918a4879a2d2d2b917ebabea230d76e9e2abc8ab8ca1f285bf4b7cc4c013b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "77d55fd71c0b88a86ee124227742cdf354f4da60"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1a001d0b215dcc906b25b523ed9fd9c4ffa49e7ff77e2b0726517838e0313d15"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "20c7b89b0b14113f4baa16afa452eabf3fa012a7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8bf914a7ba33104207a210bbbe912303db14b15f115dd6e17cb6af18771585fa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "99c25ff706f81392f5042c85ecaf006c7c69358f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f945f19dde41b2cbb5084d48c54dae3ceeecc971cc2f4079bdce1520df81a14e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9e6f92e998706cbbf47555a983e21c1d4c64bbf1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b4c676742626ea8236ca7f904e7d10200ebf482f6d10d6118e8167b190353693"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cab6a22a65f82aab3405cd46a8c59bd5892afffc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "72a8e03bd890e5d146bd5fcef18dc3f1015acd1e9a59b35c9fa9b9a4c9baccc8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1c23223a1a616a6cbf58d58a7e4989b74168840a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f04fbf5800d0277d027ff3dcd2826c4d2546abd161a426db1ad3897f4c10ed8f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3863c9e1a4ca0539f2e87c52edaaeb950180edac"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "295774d6a66102eea1ac030a85daab55c087e0ee4205bf3bc8118525e2152bd3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "63903e8682408ae398ae75533803b34a825dbd45"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "519b2370eb901cb742fb8379c8da0064ad7be07db00d459b502c171855c14f31"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "beb534bd478c8745c202bf911009b8a9b421579e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "09603c8b6ababe0eed036dee79588e70ba527f82ddc12ad1008a7e96b42506c1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d1360d134ca1ef5ebb64fbd96ce2e3bda598fcad"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a7230ad5d804ea8eeae04f5e60d1bd24d5d559b8aebe881a9e0c48a29b597d5e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5d0de19a552ea1ef9db1434c1d1b5882415247c6"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "85c8a45ba9d541a037fe5e0953b80e16a563cb162eb7f65223c20ff95e006a08"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e8988c86f6054454b1cc78d205b5331c90ae72d2"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ac4a04279504334200a85a21d42cde34f74271c87f94fc26fae1b5152bbb2a23"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
