[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "05b0ffaecd5e249cefb1451cdb71fb6087afd865"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "43b364d1c748dc206097af76d1136272a0d684c8aa16d24fed5d560c847ae145"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ddf16d465cf0c50b8626f537426b4b40436594a6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "05369ef43f0bc3f22ac11933dec3c6b8402fd211c112520eadd36b12aadeb7f6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b524abfa7c1ac2f529c005135bc9b50013e44550"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "49703c6306567f319a34e53b49f7c91d22f790e965c3917056dfb8f7d7cc9b6f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "7310bc75e71b09d05595d99a19c0117d8abd6296"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4ef50774a93b06ecd3f7ff59a1ffb62efa0dc96986ab9f5a37f9cd81f74cf3a5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c114d9b2e6b63e178f0e12fcd64564c20c626010"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c92da5f691ec7635171540851d28fdb70c9e41996857ba1c682093a2fe2b47cf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "a11c655534f5b61984e9bbde5937176577d76378"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e587642938b7ca4497d4c6963d4d67c86e6c0fadea757a3c7faa730a25646781"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "7ffdcd8573271e17621ce4e5837c09d320d22685"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8a066467b05300877f70efac77088e32e0b6947b244cd6c0e09f248e906e5d73"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e31c996afcbbf4cf66d9ea809f1b07d69dbbd9f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "153aef94e16b07f9f88da30367cb7afee6debf7f9b18fa0ef961899e0fdf4d08"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b288fad714066f4b8d0b02667dacf1d2dd77ec87"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "90b272700265a8a75a85c233e2e7454725b977a5fc4121f45b998296bed7250c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab9709a7a90de13e05e8faaf2fda635894a884ba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0e2420926ae370f8c8cea987d65b37cd63ad6a97b05556b4cfeb3a12f481a2ba"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2065b80f0ea5fc9000495ee89aa2d8a9bba85b56"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "50bd6c6fe8f5509d9bde09f73766f333fbde13bf57f274771f0b7722da172201"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "204ffb63656e56f348b7079f7971b1932ea1d810"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "69b1e930ff1d04ca10255ea3fc54a5318c4f003467f60b9b97cd660b5631a63e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "00462da062b02f0c3791e65c0078cf88e99e4338"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "94d7c5cd53965742c480ea90d5a3917bbb6c4b46de072fa6527bbb81e9390156"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94fc784e490c6d0aa2c7ec8fc2f54a69741cd9ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "40310a24aeae24d54c00c0aa7fa10d04c330f2a728cc925b08d0e6217187d3dc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9972f0605700eb59d84844ad4e147b7c6283025"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "57cb646b99c0a77736782ece28c9aabea8623f8752cebef156a6c87bb515becb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "203a9e0eb0f8c25958ec1d4a3c18ed38b43007a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c176a107844a5f0b2c8e3b6a6ec0fee951bd71cdf307772f3bbf0cfb4db7b82a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1569f6f94c026ea73942d52bf5a87d84ea05a4c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9daf609a14f6145b9cd98b7272d8b3b70a67e825d4eb90ea00a42aaf9bbe8a5c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "998d3d58903f56c10613895359143dff85343d6d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "da62430d554f256ac0df1a15f7579c6ed782bec44975c9a27658f4cd19e24357"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2fcc71b50ad934b8871d4967758fcb1e6f61ab1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bbee80c96e9ddafc0c428849766c96efc188f0e75172a8779204f6ba3b934e42"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "baa6415c0164a9518d871089612a055411650d6e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "44ea988016f1f9fec23ed41392ace7e4d9f93a0cb003301067dc54ee0de5f66b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c0bb92ee5b335328080aa457a52b9e1f77907444"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d6def89bba36c976feeae47080a0079c94d737c2cf1f01f1d571cc70c260a4a2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5ae826bf012c660a26ce5b6d0338bc1e9b87eade"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ade6d9f96be44411d8c942035e92205eea84147dbe43674b5486ba19a971540d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5d6b84da85fd22ed848a4599fb82e547fe3994f8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "66f528821f76b816663fe48ef0117703d808f9ae467a13e59f0258ff00d89e99"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7949ff995cd310d8b6c3015539e25734a2dd0e2e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "205326bee8d4f252c0a82ee5541b265c3e00916c8edaf7cecf29de3c16ff02cc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "05113f81499c3b5f2f1673eca788af8760755c6b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "652d184f9c1ed53baea0933f3259ffb1e390c6f572f241cca5e654a0028eba49"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1f8d1e25c0d9bb6551dc06a6de03fd5de30bd89d"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "497a038e94f62642aace933cabcf9d8362171e9922621d6c25c41a626c504ea6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "cea17cb7cea5a80bbdfc7272f889af2fab8fb858"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "82dabb1eef29ab0b568523fb1cdd85cddbc65be97f8db4835f44cd73b114619d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4ab53b52f9a5b85da133ecaa6fc842af4b60b9ba"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "e217ddbda60892e9ff1e3d277b04a1bc451f1ae3465e246638da61a510a8305b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "d72fdc1097fbb233157576180515bd9c5430aa2e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6e9e48f220d4370aa66c98f2a008b8d331ec2103fcdf0972ee21d5b671881505"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "d5aed582f83ad49aa7339893cdecad530b57a868"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "57d72316d2459b2554eac430a6066969180625de23e8394448dfc61c06a8af64"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "755a532583655e2c7d35a803c683d5e0b3218ca9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "20f05b8c905a39c44d50f6007076337a0fe1bc8a8dba774a3280136307514705"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "57ef03492154309079a6003ecfbd919df76a8a8d"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "6e0bf7e8ca0aa7e7af39e5266b2f2db1df28e4cee01031fc1e38d03b29b8b08b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "277b1979d1657501c019c71995c3f7134fa80dae"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "3975751902ea27b68ee7822005ff81c500c7957288471b5126de46a161776138"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b61f94d5183f9f999da3e3e5e4a4f5c00ec71b47"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d091cf7c07cef0851ba9b779fc810407ad3319eb23a32ac5a14c5be1fe7230f8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d7116e10d50e5aa8e17a6a984ec0307e09a881f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "41cf364971fdb8c376beb87a894a8b9ba11dc25e6256d15e165168ff45330670"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ab05b3ecc12d9ea744231f85eb71e41f3aa2462b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0c0eebbabe0ea23f698d21e3125b5bc0b4dc594c7d9c12088460a05de2f70e58"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "45d323da0b6ea0ec8f88ad4faf46915f291cf3b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5db1e34692cb3474057e929e2a14fa4db3367c84f55014bebd805743af48bdcc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bdee24de4338609d7f72dd702068526bb39ffc3d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4218cabc591853948646c19be6420fce65d475f9f03793f76203937d284e8e56"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "23b1b86beab17595341ea32ab0decadb5fe845b1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "30d66e6c3a6b3131317c8bfaf198756ec2c88ce36d0ab3b46a05323a069ef4d4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "05ec9f69f294b564ab495fd4baa45f4bdeeb6288"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d3bbed80a72c0865fc9f84749245baf9a0c8d932827dd57b08407d4e98d7d7e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7d59703ced606770524cc3b2e99ec16489119433"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "aaddfb67cc8eb24367cac5d3340d2d5d02c679416e88dc14e4047feae1e06fd1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3097a4ba50562afcb6248034e59435be58d67ca1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "c51372c9e39fceb18fc61696eff5d9d8bce52b429e35945a3d7d388f8d6338d0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5a770596f00ac6388050e60965666ac896ad7a9d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "ec6fa791730e1f4d4df1751cbbbd1a9d051117ba98b31a2ac87d4a907dbf02f1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "17aab417967eda262f7d8bae98b4e875750bab35"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "afafa79f46adf70d1b110d0e52cf981932adbe1bbffdc789b7e222f1b179b4fb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "13468f166438c9d95a350bf0be9ca9bd3b1b3cd0"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "75ba629ed72b735d8c6f12b722e8a11619d4d44f02a145d76d858813a1013a89"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "52ec564424406b54ca5dd4618bb4ce21453f7b01"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a1ae33b7e3d991fcbcfe48845a3e83fdb1cf9f76022d08f457500206baf51f6d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.101+0/MUMPS_seq.v500.500.101.x86_64-w64-mingw32-libgfortran5.tar.gz"
