[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "5a9770850fbbe51a35a9038801aca8c67afa9cf4"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d100668c80ee6b6669591997329ed2d2e2eabbdb674e1ee597541fec9c9f8a88"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "6d152fff7b34d696538c642db15b418d629c7eeb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "86ed1a140ffe4db8ad985dd1820934bb7f62f939e5c143dffc15e93fb13613bd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "aa2aece8eca29d4ca07f0210c4216d4865741278"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e7a11a04e83402d815e1a4660a72cb168f3a22bc2a7ec207569ff9852b332d26"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2e1506965fd30aafe2938767a532ef80ecc1e512"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a56b65793e6e15a657733aad4fc2bf172f260ce9a8d1bab9297995641ce72e96"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "905252a40f0edd2c0be453733206537e1ce4df62"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9296220891bb4e5fe84cc37b653982b350b3a2dbfc8834b4a3716453a007c8f4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "6a330492a798282c839fc8ed6669adaf51e41be2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c7964289d9eefdb6b5d970da947b568b37004ac6f9231f282afb5e9ca36df4fe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "4534de9fed07944173bbb1a41261bd0116af34b8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3c7e94dfad78fb280caacdca7776e7d279901f04d8a69d6fefd78f04b22fe897"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0715840aaaf5f9f506aa06e01a71dd4bf2312558"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "02599893039c64aeda28594dd0855f5436c39c20723d91070b8687284c684615"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d31fffacef50d67c5f88b3663071d7e47103bc67"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "815c0f0e3fbde637a42e707bcc22e4b80951e8dc1a3d3e611fa20aa020c6affd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93f48026a4e7dc19f72a3d21e5c11172ef169a7e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "27e8117ca4cc282d0b41f296c110b86922cf37d441d69e85bf98a95e2b8e1da3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae13ad866844f25d1a32664570dc1483fa657326"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a665ece1f08b16b3d70d4b386f23a979c4ed2a32ed28405f6347154a3119aded"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "38dc6ef9f1be249edb4c7121f730dbed88911fe9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "860299955fb89f0b8eb2caf819aad2a507c41077c3a891b1d1104ec40727ee7f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e315e56ce4f390ce08a1882c9a982875f3eedfc4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0adcaa16538f20a0087af5241c761af3179d20ce2cc26dd169e3464c7c24a4e9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "476a2ca98f9d20f44992628ccbf99301c2e04d8a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ab2489804c5bad6491b4c4ed6a68c5d31bbd6c0a7ef76ad8cecfe547de82d1b5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b0666c7af8e949a31e84192ad777f429db580fc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0711318e627061e76c527b93c2475547a0abf5532b86e5656becb431c7f37aa2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b37956c0936c597e9e7d3dfab99297127dac94fc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "085b2e9e1492e2f9c9cde1b0a1b4c7735d2abf4283b3bf3d78dbe9b1f394eedb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b982800bb703dce33f823abd325c5ad5d6727a7b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "37e1530aa578f8c3f0042a95b8b1a25760d852b6d13d2a7b291f10bc7acf2890"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1435983b0398a16f248af8d52897e4f3dd47b7c4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "46f2a0950d5e2ea3889e789d84cf82de1a61d42cf2497d9b614f66cb11f68197"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0b2d8c83e810543519cb3dac7d1299d0268b424"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c73421b6dca02412b385f2357101f2cee4c4ef8b64fe4192d55aae860e7be3d2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "440504edb5c871e102d528001a701ca506234c92"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ab5aabb34c869f252840bf06956c625fd67521d85fed8557a5ac6982bfd230eb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "106cb4667d8beac483bbd9a24954ab2df8b58740"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ddf54a97124de048700ae15a3b7ef80098d8b512501569d8387527de3dfbda44"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "d554d2e4599c97dae9a75a993fce1ae8cb2c1487"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4bfc068299ccbae100a526e9c49fcb4bbae7dcb4e31b3ceeee25adc30031d9d8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e4465edae64cdfaf20e312be6ac634625c60439e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "586c9c134ac5d4bf51b22d1bd6710bdb414f8df29fccfd1da9d173723470099e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a12ff1965f9d59adbf8e51690a3ba5b8a2425489"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "941ff0e7cf03bbc4dac7db7b287e519dd39dab78f68440d5407fe8d21946ccee"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1ba3b1cff23930f317daf41fb8bc7175dc06647d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1567522d8246272cdcf0210f0908d1e8cccaff1410a9ef76a2e310cfe6d0c61b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0e0f0b35006e718430471a8a747291166ca5b1bf"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "88d54f66fce7cb82b6b9a1c625d3454315963cf9b996cfa3c30c52309c69806a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e91bcd1d3c12bd60e9a5ea5006edd35090eb9054"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "c530de4dc35f9452c1aa65b62f6a6c72a4bacfd319e1250b4f19d3e117f4c172"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5a6bbb50d6cee09630e8d4df96257a729f4348e6"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "470dced3bb35dc073bef67f70682339e6213fd2da3519bef8613aa3e1121302e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "f25b0dcda6af63dc521b0b514d1a06d98f63917a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3bdbcaeeade818f55272b404d7a235cf5249d3c154ae865bd8bde394adae1901"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "c8a04770a690ae17a55dfda14258abf3daaba8ba"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5665260da104e42a2798dbf87ab766c2e16201d568ffb32be66f665342660792"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "df21e9523cf3e75767bfc400faa1ab1989cbd4b2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8500353e43c992b256a55499b3d9c8480a6478f94ff28e3676d13fa927ceb481"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5832c30a559270d49043cc5c072dc4534c8a67f2"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1cce38b68c319713afbbc139e072bdcc07ddc17cd7c656270f1756d3da91beaf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1d5e1679233f2dc8127a9fca5aff3c8f5d7cc5f5"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "269c5407c8d6790c787ba9b26a9b94c56edd8fb2c02e72dd6104612e4e817bbf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0a5bfb9144787253345545bfedf9a8dbd7c11998"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "c63495b27dc43ab7f6ddc43175381c571b3e3044635bb8f6561369b86064d950"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8b3d8b996ad1e4aa9d569f13ef4dc7cb4e19a8f3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "798543cb50783dee6c324612f85be0aa12629566c5c4c05844697adff140163d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d7e8f9d70d3a1c2380f37a48cd5b0f62fd611ce2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e63b97c870874bb34dbdfd5e6da3b4309b235163f42117f1d86a0a2b67e97797"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "032beec945d79c4e726f4bbfeb00e220bfc67ce5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3c7ebca365f4c450e885891f6236d47c87fe4588e7d18d176d4e401528813c36"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "58f20e7fb379074ecb38fe0df0dcd1e86c3af7ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0bc6468ad96c7dad0a2fd24e41137607c8e0927adcaaa120af6a4a7929f88fc3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "10ca082f2aeb78ddb191d5881e4a68eaff23fc92"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "19ace622e2b18b0459a267b9a84447ba8a647aa5b3964b82ad52949ea3e2e5cd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "693ad34aa23d18486be991cc7f6e34a88384e0df"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c7c928e9c17bbcf882d3d09c4082728d51764bae9ae8ae76b000dc4b24cff51e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "22718de05f04057a283abf7cdd143fadc23d7878"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "c60e374a7e7c82046f5e6532c79109be4135b5539fd28e12085b0cb655e000c3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f8c0a3c991d8fcc4bc9b49a652e9cca90fd54292"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "d7e468c65ce45346d469d9a2a7beb6cedf88a6c58d8c493fdb1ce5df10f60ab3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9f4293eefde55193d2328ef5e522895952f2d5bb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "aee7f22f5a8c9b603419c58e758fd40efd48d9538df2742ce917104674b749d3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0ebf0524218f1f5a17e6e20c5ae466696ced229e"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a544c94eb5c12624e507623ea3a857413c73257b150a03c42129d1a8fb000eaf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ef7c69244befc19fc5f591d9be36fab67bdc4b37"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "fe75a8e5449cb08e316f9ed74d8859d457c0f98ba3ae55a0fa9cf93e83562abe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "50baff5d2047c1d8fba6d189f54370c9bccd6f8e"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "e5b2078d6b0d52fe701086e16362064382651c4f7ea8cf29ed6db827d620d452"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v400.1000.0+0/MUMPS_seq.v400.1000.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
