[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cae290623ae5a917bad0fa072923240734a8ccd7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a74a659de4f7d96e959c52fb56e48ed2ab048a49917263162f7ce85d542cfdc2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "ec5c4e4b35504f7337b7b0d565b0a0dfead6f286"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5abf6eb3cae12cc329b7cfca8ef073f015643b51956b63d1186e6d1f6364c8fc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "378124997ce4859bdb237d5a516d6f0fe769cc30"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9854cc193265466fc92616891c2b00abd2b79ea7852032cfe8b772937ee412e5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "f332b6ced17212e52412813a0a4550cd102a0cb0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "08757edb059a2de126b501f0c7afed393763a77ae00a3b7b6227af08a7dc5d69"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "c2383f2f1ae8620a951cf6504eb29daad22a84a3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ab01cf88168334df6ef325445fd1d097b6bd8b9c1a8511b0c7d5f86fb1cc836f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "93ea1f272b40b79a0cb882976704a082a3b6a2b0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "97e3f1efe6d27415b30bb58c3e5f936f317476184d5bea2d8890f53f96c7dcd3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "99bc16c7574fece8444d3720f953e7dfa8a868f7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "96268a962aca838769b4a6e09a9aea663b303aefa33608247e4591b9b604a45b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d26ad212668a662541d19501628ac0c9816340c6"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "6c862bef49fba6611521d824b911b2b22997fd8b78b31ed5a20b96752d4e00da"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "e4f66c5d01aa6b2c32a0a9ecfe51df01fa771b82"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b7dd4ec2906ff637b3ec7c2d0a45e47d878ccc670f8dcf71bfb8edca384a75cf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "66cd5f95b6f93f02aa1a0f85aeccb7cdb569490c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e3ad332c35a84ee5caf1c370dcee77afdc20d89d61b8b1b9d118d46e13bcf466"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "738892cd52d194c8ab1498984f52c8236b4d6be1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "11390ae1fb84a319ef146b966c805b5f19e90240e7a9982e02aec0298c19b318"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1413294e8e2abb645f4bb32f3a0ce84b9919e6b9"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "358d550841d53806df67c2d02dd088d28233fe16ee64d4b42816a1823d5c8088"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "1195f46a59ae3a93c4019fff99672f4bee26d678"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e2e5e68429d504091ed7a444e2d89153b4c284fc34d3ebe2ff1ddff7a57442e3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "28fc768ba3b858235b2d1d42abd0dd4e73a26a31"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0a44e78fbb55dfda799a0fc649e5f54cc757848a68544f9d04f2a1292668201b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "58351feaa4bbb4d8afecaec8feacea8a920d1c28"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0e611290adb81533e333afe3ed36e009e3ead2fce6a67fea47c7e07572d1a87e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3e97256c5029c35e69d441daa9a913c1ed9e8c4a"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "2167c4e7c5d0edb64632dfdca8c3519f03d0714bb83ab4bc9ad7c3eb5af18650"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d22d0b66fca0fdfda76f4d0aaf90960b7a7938d7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "11a35906b1e0c18c50820d6884b0fab8277920c864baf2ea5a55a7ffced2af2b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "84ab2b0772f53cbb0c1ae8fba00542297e3aa16a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "900ce1595aa0cbd853fd9c68b84f9652053b0a0e79167a527923a7987491bb37"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c01afa439576fcc210f9284e8509793df5e9fc7b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "58babb7b755b471d876faf5f057697abd0d693560284bb420f167e8c63a4444f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7bb0a693581e88f964532326d70ef40978a76f90"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "21c6a587f0772e5d9f987f80c074796a4b461770b8082f2c319c89710a3fd1ad"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ea9f802d9da7969018136ffcdd3975c7a82d8d8c"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "564197dd63ead18180a7dfa85c3d18668ee0a595fd13e3319b9ee1a9a4033f50"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "abe4a23d46b1081db2581520a1f6df79952333bd"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d2460a737ed2b87909160ba3bf3350c4a9a4c146b1062e669ee21b8b0d1b69f6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3be80e94913c1c9a695e31ab9a0c5eccbe779969"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "17135648c54ff4868b4aeaa026421b2b778c224e2a3c8f7933b63e274ce0421d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "eceb9c3242c6e5a4dafa8556427c1b4e7205f7fa"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "90adb917a394b6e695827eaf2aca8dead6a8018f5953792c7c8d2799f3519355"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "6d6b20a47ce03baf0ef8c5c67a4d066512b79c9b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9b40cd805315c5418c8737a9d3f6445cd3d34d66c7a9a5c9b8dba2cd8fa52ca1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "65ba962b92872736c7a140b8eca2c08a95a03108"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d513094d47fc9739cf097876b5b901bb0ae0e4abd97314a8fa3ec3a7d9f1c18c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "db92a5543081dfd984dc1ba2ec13fc102392c91f"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "baa16bbfcb22a5096ed567be1a1ba02d388cc3e0234cf43923af25b3c4f14041"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "14276b0a275be040a8cf0686f504547b2eb655cf"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "4392287fa54d961ca81d775e02c75fc7bea46fc7c3fe85c36ba135c3e9d4424f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b898f72871bfa5eb2e0dc4488e60a8a476d8066c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "854abff71f5e301a394b4d2ffede43dcea07c90deaff14a7d1ae865389120371"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "278469f7ec048a256713be8878ca7bdf987ba418"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1c984460ded9c975616e9ad75328a80ab3d46ba4805e0ea74a7b18bfed794f69"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a8c0c07b5e678bdb91954e9ca1a8abb4e1d814f9"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0201e99098706b9c1001b9b5547032c95f4666103b3d34b884bea23c702c0247"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c9e7afa5100a7fa3c0a24a736b4c870dcf6d2106"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "61be1cd034d20741491e17a85ad9783d26c3a6449269aca45c743fe972ae4bfe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a098e88f9bbcc9e2356ac113638f5520dacf9995"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "45cd1338b78ee9db5f619ee8e519ba6ff2a2e5b9dea5af4d1eaabae8ead96255"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ea3c13a6e3ddbf85cfe31616cec076565815db19"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b6530ea71ee2f01f92bd7acb1010e431d59823eec5df2b86d3510140b35171c6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "04f8582cbdc976634a35d34c75f35ab2a524e3fc"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "8c6157c8fa052356ae57c260e672a860e1d169155b136911324686fab343855c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "ba74fe7f02137acc8d776603e38766fa424d73c1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5d147adabbe5c1e7143b3c904746660490cd5c413b810ba82ad481c1a2c9a957"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3ea81764a2e4def59e236d8a3a3f8b63257ddcb0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e3ef4734c174108093ff63d0ba1e6edf356f94a44557744938a803b3d38d512a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "c253192f62c3588a7ec031f093c9858d01c7efd2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b97ef371b6cf4fc32d958e54a74c057c98da8274eccef36fa9e1673f0cec5767"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "95bf19c0e36759a1d1f100b8ff5eb035534e54a0"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "17849265f26ffa9942eaf4fdca37bd6760732c0a703e731bd5f337942dab9f8a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+0/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran3.tar.gz"
