[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "405ad94133365cb9096cbfe40dce98e76642611c"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "c5533f233e91e510e9e7f8c021e3574a5f42af136738c6ef1d1b8b033d476c6f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b539ba50c141d2f71c56cc61b23cb54394fdfb19"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ebd51b3210e6a7c54be123dba98e6b9c8f4d5687a97268fc93d6d8f7d30a18f0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "25325757d119ddd8117dc224f073eda6efb5b009"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1aa6ab1ef320936e8ba50297cdcfc33ee5b9de242169f6707aa21e3cb34563c3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "8298b37ab44b2b0948bdced6021bfb1e0a274042"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "613f4a8464a665c1761b4322a801cc2a827c708ddef209b75ece9a006ae8b39c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2f585ff41a1e5ffcdd86885b3af43b959c226562"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e6833f509f7a2143182442e7240225c70b235fc6e8a0e00c4eb8dcb192d46392"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c1f441dbcc1af4b5404cdbea188d6f69a8e1b885"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1b4255711237828e8b8f5bfe4eb85386c2d1995f3551d1aba66d2e8b91bd7c3e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0f038a801238110f4d92b0fc7358e2c28a51332c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3a288151d32b713024e7110ad18737c236ad50f1d5cb2f7ef26ecf31322cb5b7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b4aed442b55f17b4979d272aa8e8261efe4c74d9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "31cc4222b8af2c0bbc1e499de67c350d4800c62f093e8500a167e0c7eb4d58f7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d5ec23acf3c8a83c3794b7115ca5dbfe1ee27cf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9365d35ca05864702e0cbb9790bf2cc312b27cb6a3b9f5014778f3c7364572e5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d344632ae6c7025aed10ae2f0fe97e96daff88dd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "edee1b11e0b28ca566027e10a2c97169278bfbf9cde14b10c1630813474376a5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "933052cc6b338b9ef6ff87e88a328e096e7ec036"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1cfdbda5847242c7e0fa2167f69011cd35daa92964c3750f1e5ee469c140010a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d2540a19146cfe223b1bf5571dfcf6e30b08c41a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "411bdc673d5d46bb7f4edfd6c1e956fe80a263183645af12b7a0eda84eb759fd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "919eea2a146a8450ea81eb41dd3cc3fecce9033c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d0029f2461f729ea379628a37b8625c57502db41de80e5d84c7f09ad454f8052"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d53988ed7ae4b7f52b9355343dbe6fb244a039c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dd5ec8887f9123e0c17aea44f15080d2d2093b4916339e0c3f6404019e4cbdb5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5e3496eb70c3b34dcdb18126830c28309505ba2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0d44e8bf79cb18b23babd43bc1dbd7654175f4c36bd2db4a81e8ac334faa954a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c700a427b01d33ef3255a9cabf9af63d3e61747"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6911719c52a3f66b25417044a3b00081b6fc02ef7354b36e356c822217d0a114"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2679aacf03701f7ef5f3c1bcadc317d1609f185e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6923ddc59df96ca942c8fc29bab8d2426fc1c97176e881676879795b198a674b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "533954ee1019c50fba60c379300cf96fea1f861e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bd570ee932af457fb6e08d367a4e810c511f861f31cc08208296a9046619f793"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ddc90fc0044301aad39d31e46c1f605d07022da2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a1066556453d550d92f9b75adc8749c07231c7fe39d3945d6cc69a709fa21c89"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "396bdcc43bdb8e5c8986af4a69b0a2d5144032cf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "45a2a24ae363160b459ce397b09874e0e28ea9c25dec246531105b5ef6fb902f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "cc3db50c717acb718d9724bd2142ffa9308ba403"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "01304c7545346d975b0b1179e1001adb74a17f85b0248614d11b1215ecec03f1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0c5301ef020ff3a82e646c0059aa53734e127e9a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b3c5e02c9ec1ff72efb1b89d940123a5d3b83af5f9ee42d8d88886000545a2da"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ed4316e245d25d833719faefecd2f5f2e8f7f61e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2c11beb8477fd7937e6397cc11df07276e36a767fe804b0381f9ea1577d859e1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3b64cca9d135c48853e3b16a85f6e87e99e9290c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "152be71c3dcf51369fe9df193d2a4965f8729ec42967720db227ee735dc16b0c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "89c4e587a79178af09a32010dc50dfe0b36d17c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7a38871350b2c9789bca08cca01eb5dcce3ec562cc7f6a755eb367bb573aa112"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ea1999a3373f0ac3f9f533f2b4a94f7458e1bd43"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5e3e88184651594cb3f6f9d2f55db3d5e639a8eaac0cb61f57bd042f14492ad0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8bcc767f1f190a9e2cd54ef72a9d4dff346cfde1"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "8fe3a4fb71ba5e9c8fcac5588dbe041bcc6b908d4adeed4d490ca390d4373872"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "58ede053a18b93a14c7188e0a6ee6d7557a083ec"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0a6a49519af8d18663f2846734fa2a50def69ad29aa3d542016b560d92413485"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "edf29bfe3ca22429cc98f5417e02a4d0c8a3fcb8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "85805e0cf42867051b80055b479ec16d74e11155866f90acbd6f3e043398f706"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "3c8a24193faa879d2efb32c0b1154ab01e58e58a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c5b8919134de2a5e9baefdf11d4f0a895c39f67b74a4823e9a8c3aa9fd94bac0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "7d891dc05293e19cbc3facdf89a386392332fede"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4144b7d471177cec97358f3d26a237afa63862253c25c0095037160c66793bb0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ccc4c44a51243735a84b94b8bdcf144d05efcc01"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "a88a301442799adaf042c9413108a7c5e59ecf6e66d53606138148787123fb28"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "56b695db2de436452d03c1f56148250b7dc6bdd2"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "4552be418bec366f8fb9d05530175548523457e1da2b9b65a177cc866d08ea36"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ac5f1ddcd88ca8b4c58fa36a055f5b3b6fb2bda7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "e7b46b8ae5ee0697c3938587f5a5f19d687bfc35225f692a04e8e50cd6002fae"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "dab2ac532d15f915bb0955eb7d082f97ec228185"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "04eec411fb5cfa11c603bf5a06b0a6a166c94f99652ad93e940b9ed924700158"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cbd46c3dc77e9dac7227f5a9424aa89e9440b3ba"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4f0633d785517ebe819f6dc9e9048a777455ea26e6d90f509de1c3f07f21594b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f2f34d7114be0239afb7808410f0231450480b65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bdb802a30c282f2d77cd9f8136df5efde83d6f6c059915dcfb464e1dcf64e35f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "80441e99ad7be2d9bf1ef83be17a8bfb5c73b5dd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "76f6b310e5ac3d634946f67d6d1484a763fd3a6d9de834833bac3353bb83c5df"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "44247332a942299e8485341a6eda0dab687d3b6c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a336d7664da477454f8c8761c8ec167d99e63261777104dbb9f1559ff67ffb87"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9b2462fa70269e92db1eebd7c147c89471cc0903"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5a5a612cf17a4a60984834d18aa68a8a8f9437560fa4eec1695110ad7475bdca"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "05bcda747740728ec75f4ad85e3d7d7d178f28f1"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "70ceb8178ff060c2e690229a855ed80f765106720b04b5d521a0ed3009889340"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "fd6b42a86a9a878b2f84f205363fb50b4f7595f5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "27f3e6296b8ea3cc8cc4d7e5e2dd9ed274530bd8603f47d78febf9f804e0246c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3a341e7af2c2ac331beb1550c45f0bceb8db7d8a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "feda4facdcebeff1fa216db7a0062988abeee623bc955b0aa562eccebb67bfe9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "908293e15e6c8042ba0dcd77df4f1d8ca50cb501"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "cb3688ce6c12392f33a56ade70d0a36ea379f1e203f5aa9a800b57dc7cc5ae7d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "91a3b44146b95513a00e70e93c3ff4edb89a9815"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "598ab7aa34eaa00933f088b480451bafa7ad8846f9f8bace4034d0317cc9009c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e741d4aa85076764a73f0134b4d67a2fb8d2b50b"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "6d966a44c9f32e586d84f6431c8bbd522be0bb41a514f472d145b7300ced879d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.0+0/MUMPS_seq.v500.600.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
