[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "7039367c0a10e855f047f9928586a2021c1decae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "99b00959c57fe99dcdcb68e11365c1369075ae63957f771283f1e28cbf0a0bdd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "fe96ef89a25bd3e241bd227767fa880333cf95b0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cdc9dd0c46a3d8207ccf98080e6314abb89c8b33edd1acf8bebea7fa989fc0e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "51439a4eeadceca9a5fdc3800827ce317d5b1c11"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e26c4f9a80c3899eed8e6a83d6c0ab9024aa75837a864499059d2e097d866263"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "74ed56ea32f65800bcca1d429571dc5cf33476a6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "32670f72529fa5b49686f425d74e83119cc6c6bf4a64fe046e9e75b6ec13d5f4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "81f86a23853cfe63f67320b3d106e1beaf638daa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d2a050163a30a1e3d3e857d274720cb737d2bc7b546163e1017434462670d16e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "00cc48b338fd365acb62439fc06d17395dfd9ff6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ae369f20acda2bdb705cd61fe6b55ed4363385c0659433abff13837b50771995"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c586970a0d7950404b11eefc6316b41c1615c7e3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "be2aa3f8618e4d3929fc8ddd2ff87288f2566393917ad2b5b94393551161b773"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cfc727a2507696180e97704115dbbaf4b380b25"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9fc2b177bd4b15524b7a20259395d3838a873403f49d2691ad83fcd73cb2f03f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "970d3563b6ba14bbb2d24ef83b5a00633772c486"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4652cfa3e0a74e2b2f4f3b58b07acb6f61f3b2e8c215fcf009ecda8c2294dc06"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4275bf6c97c0293a4f6a39f4bba2439856c37e9c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3218c15211e2f8d5e306c10d7aa84acfc47795167490f3ff61ef766871a8194d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "736373d1458fbef50118f8f2e023922092c97a80"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "91b4dcfa663bdc1dd45f7a35cef67b42f292301b8a6cfe9e2cc4f4149de2e482"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b38daaefa565dd0f44226638dd233c10cb8a209f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "85194446a2a3d9d6917d925976616fe07199d1eccee4d5b87e3a916a0d7e764c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c1515840d1b91542c2c6bf09901f4c81e9917fae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "592a5beae19f3ad9fa7530152aee73d0243112b8d10d53d20df9f5cb6c5f43ad"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "fbf3f8caeb66ce769f3bb419767c365aec725976"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5e0d1a9349c7ccd218e1652ec3af9e6bb02937090412a8bf9903df1e54bd587e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "d4fbb3174a0825a7cb0e9fd23c645e3e1f507b3d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f91186a3a81c694ca06c20ec99c12ee596c279d6eab0fb0299f60f9092628293"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "12734d2497d40ea44d0823272a2462212da0c060"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1e03b5d77f731617d6caba7dce2d4e29315253c57f9d951a642d1ebdb8ee0052"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "33f99fed4887f54e69e47d2984be29caa3982850"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7990b1c98e5f19748e0480848fdd9eb02768756db57db435afa674784a7fff28"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3b5f8eb6777a84c12727d9100f2f6f7fda03b99f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ded2231ae4c53013274758ca246c5eb522216600f1c3b0d64ee0ef4838a924b8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1a4f7bb12d8fdecd397a5ae98d89d1f4304ddc0e"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "47454520c9244ccb67b7d19a2dbd06048e63e7ffb4cd7627c8f4e1e646ebdace"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "96247a9fdec4e266d3f29a3dd85e0f241b107f1b"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "9dc0f30723194c346e69c1c7c4019c71ba1762302b1dd699296585456cf3d76f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "97860fd07fceac51d2b225fdb66c01460bceaed6"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "12a871706b1e5dd811563fc85415865cfb24a625c837194aa113058f61f984d0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "344910f1eadaa9a099767240eb0192a0ba59b77d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4dc3f7bc9af69fd12fc086b6d99afb6a703cf1a9c9e6efad0489c901d3e052bb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "521d828204c4aacbe072e89c9a5fb114271dcffa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0632e73fa9e90f4807e10c85f36afc3d259d8ec52e5fe4d1c9b8d8e8f5ab1c10"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "9c207a336509eb9cf1b863d8aad8af987fc577bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c708ddc592040c1aafd92f9f6bd568a160e7142347a77db2f8d389f09b503e98"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e45ec6c5693d1ba30f52f506b79d62180a378afe"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "a438ad6d25598ecd82ec35bb34dea56070ef72e261dd866d0e8127bd5728941e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a02c44dc4916b747503661217366d897faf978d8"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d73ca7aa9ff624793feaae3e8e657312c9cb7528dfd89dc4523c964772c4b3e1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "77d1c5e720d55e9fc1854099f894cf3abcd28cfe"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "7555e147edf71270a911d8f0ac8d8d99af6f666d6966bbccb0843701d5916a9a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7c71eb0703663375d9f35cdc16a989677ca6ab38"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3cf57922467c0244c3430b4204b2dafb66c942c046495e26072ce46f75194544"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a50b6b47691e4c278ac3d424717db0a182c45e8b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aca06e3aca4751cc721adb511c21433938f6b7f86125da129271a88beb79b5ec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "aec8b4a28cf50c5cc3a8cf9cea871fb7a155ab05"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "61fd006aa2a0530feaf44dd2cbfa28864371ec566d321ebfb1a4332f1f335df6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "91bd1b97582723d937555b87d85c8883392d5388"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ea04f0242a75ef86c6b9272cb01aa59e3ab99fe3d54359b509f5f5f557338edd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5f3f5e469c7290771a81187ae3daef692f39828e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9970436595bb811a1780aa0ad7af7d7086c6d102eef27a4f67521427601e1a2d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1a7ccb35a50505abfc39972b5ab93f892adf9d34"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8678cf6e158c0e59940327336fad10b94fd9068517ebb1179a996e5af3cafd9d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "117cc8d2400762e836dc59709046c1428a2feae9"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "282d1bc913a5d9f05f2ac8dc63c7ae0b17e0da1f239a57ca63b5646f7de96a0c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "45c04b7766452feb1e1f0f2f104b7d89fb5b20df"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "8e922dcec0b35d714baabf9564ccf35185f214f253f573154e9f82067bddca7e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c60628f1598c9e18f2f473b75946d7db5c2aef46"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "050a1f3ba91815af5a3bb4435a1683cad9656a8ee9a4347a80af6cb915e057ad"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b2b3ffd49045369ae473445afb65cc80416e602d"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "f068a0962ca70a66c9df56ec059fbf54b026dea40471f7ef863c10fef7f9f13f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a4512e25c346142a04fd5c8a0cc18874081a9a68"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "67411ba7081a2e8faafa86655acabcc7b25b839060de8910b88267c0600d0c79"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "08ed004cc64f7f83aba53334428558f193408b26"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "2bd2b96c16a4ca28407e1d5a05190b819f5e4e9d372b8cd9c8496c5c31e4ec78"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v4.10.0+2/MUMPS_seq.v4.10.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
