[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "eda5bc8470ac2e1af23bc580cc8acb07557b1559"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "f737a3236484eb946cf821f95bc4eac59cbc8954550df1275c2a635c435adeb1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c4f1871f3bd449958e784ebde4d4deb095f0033b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cf98cecaad3d66a589c187877ef3feffc1d58d62e05b16a70c4d1562f2195631"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "9bc129fd2a86c7eb735cf2ff65373825cecc6e02"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e09112aea96204dcb831685359ecc39d1371cc3f732726aa6b69462d62c42ebd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "4077f9ef0808b0c02a1c6ac4acf4dac51f087bb6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c3aa47fea484edc0d45c35f8a1847c1a0e391cd95c9ca69ba90d7c58421e284a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "251e30949cb58938bcb86c454bcf9e804c98b2ea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3316ac66a3ce7512669b11cd2e2aa9e61b9013c04bc35854daef33a129b8ffb9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "edf621a4326b68642bd4a2560c1cfbb0a39f951d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c56422a35c587d8793e4edf6669b1850ab335960d58e352979e8c8fe839ab36e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "88402df7c07e68daf3e65258d09c1f62e7dec7b1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4aa152df2edf03af322ca707e0025d22e7bde3c79ee3fdbec4620b9c63611f69"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d84c9eb35abc78c3e4f2b3ce713a205e7c867d6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d53c364548d07fa5d2e4ac00f121a947834e60084bab40dca581d5acc9e546be"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d0cf14550d14f236cfa9cb58dc5daec8a1e8b05a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d8c7dd73d068915a01e02efda6746c6c5b568c255352d9921312bf50d5a1aa9f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "77712d2ea836a1ccdfdeae02e3513cc6a22b5034"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "38e249a7543d84c8baef7c051aa7966485ee69c15f934e5e31c700338ae38fb4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71c6dda508bfc8f67cf3059aa7b567208f6ad4c3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6fb8863f0266cb280a364289746a76303b59e60dee3f9f38ee771095721357ae"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "719fbc16b70303e3f6393ccd00d053c5de552977"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b12f91345a1177419b0f1cfc32058e9851950720efd68d1e70646e6068b64f91"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "18269c43c18e70329e640fcac1c68044f50d98f0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2d340ee98246fddf48ca8949a7d0d7cbc67e28900a8c0f461a74cf2bb715caba"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f8869ff4e5b7d909dd912392f3be051c3c0d9bf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1132f8bfa32feb828a4faa0b027221fe4dd2baabf963688cd6bc645506eb3c83"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5eafe0d648a4cc36303ea4718c2a7f45aa2176f4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "57f23a9f9e705d716ab147b127184cba1085b0b22b928cb449c93ea0fce66d14"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce50df0b67413ffbaabe0946d522873ce46ef7c7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "86cd406d3eb4510f86bae75fc9265398ad169423f6f3775f86c5d48a4399ab89"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef589bf9ee02b495f333789a8b477a2b8c68c2b3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fb7988ae38c7da572b3556919c3b895036773f58122a8290a7ddd100b303edad"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2c209f357adeaa5bbb0afcd7b0beb6219b9070d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f3eaf6335655247df6c2b9819b9dab78ff18d4069ff0a0169305cd4dd9dc0b51"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2536aa3ff8fe2a302ff59e606971b35f9eccc6a9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8e509eefebc53a771ed77c92b516bec818fb9e3c9d5b6175863b89410cd51dfa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7304e053c2320298394b7f3a39de130f1d2f8a46"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3628fa7fa3e303c22c5552d2079959b53d6539f3a716af63067c18767de709b9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "b102875b17dd59c3924f9140093eb057eaa1428c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "14b9e91c6aeba3a3683f7e84187c17bae931bff9381fe09bc6686b6ed3d5b400"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "712ab41d3bdb0ad33a921d8698bbe1f9ff0a916c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "54e45ccb951b47228dac2aff823945b663c1a4692da0501363bb89795639eb3a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "6da158ad904d86bb2ff1754fa68ba0999c2a2fa0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "68e26ab643a2566dc3293e64b32ffea4cfd0f370325340443431c3f307d064ce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e0d99ae796b69e6dfe325b9cbcf08b49ed503b8f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "864bc8b50127e0c975bb1dac7a4c35fa4e9e8f3056d8ed64cddd4ef4d59d46ec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7ba4355dae910c773cca061649ef292655a98491"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "76a2fd7b0a61f8c125db2e0faaa6da3512d75ae2a4cb3af29f62d4befb34f9f9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e7d29ad8844d030d2b71185cba5b449a6cefd391"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "660cd8bd0e8de603ace4695748f807988ad78d516050257b34fe7e16f868ecec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4bce79d6a8748f5398f598cf61391324818ebcaa"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "2a7635bb873e61361edbfd1f7e7e869843da45b6eac26e75ea997c4cf02afeb1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "47851ed5a07a4645d5773b8e4b5d590d5d7904c7"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "d740fc47358c664ca61532528638ba282ecf1f1f5d3e662060b0c4af3884e72a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "c6d2f427ab3fbbaacf1ce94e4b2264c7866e548a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "be4289267461dd68b967183759f46936df8b8ef5482daba9af4ef17ac50397e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "06c9ef7d2016fb673b20850bea8e2ba7bcef6659"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3c6eb08197a94577ed483a7e1267b6b4e63ec343e751fcae68bf3174153219f3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "8127a14667a7961f80d02c81a31e6798768aaf2d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ffbb658ae8877d2014c3b6b6d3f5c080b53c93f7b9f02229220a83b7d35f4763"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "550edcfa74e1f132f8ad0ee42b7de12dae7f4066"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "3fea067339784d4e1eade2e4943ad9e55a12fb59ae43fdb8ce00a32bdc0dcfcf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4defda374f5e111859666e7f647a352cf9b4f72a"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "bb3c9190fba6bd7baa2ba7df1b53e459b435b6240f2f06339918866e175da24d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "30b8411da92c0ecfaf782634442aca3ba928287b"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "8f44a260126fa9a9334c995cc5e2b4d14050defba153d75ab65cf2b0e9bfce3e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c8897f52ac3a289ad991354c1a813fb2bff7f1ac"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fe97ba65cf5c797018c6d7ca71adbc2ce33ff9e822c2c865178dc9af51449b13"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1d534e41111235b4ed3bc9a90ee6b4871c8a5d03"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e82e9f36c2b4359ec7b84b44d80f44e6c1f758e146db61e6733d7b8ea560ae94"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3b9b41fc05c0d829f406e182057e5cab78bae564"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "86fa3c396e267f36f7c4f0c96c35d7f16177da9e91f2a3d366adda5203f2c631"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9d9cd3162fe585b9095dbd983466eb3436502249"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2756fd03d811f076f793f7181b55b23f6c2794290876746738f23e7d388a72c3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "33a5eb7dd08c476fd4398e8c14e25db0c1be0c8d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b98e1d76c6b66eaa34f59f99ac18fe38cbe21e20aca676ab2108335ae0cc482c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "062180f65994cd0dd4990f79bd70235f091d3b2d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a0e955f9561400e263ce2040343ca805587c82953594e559cd14d2001233bdc7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "abb1d7cb135dad210f6b59b800e5e7f928f956e5"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "1e2b3fe47276780b9d554d36885c6d2db0503c58891e84d1210e52afa624f342"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bdc42c12ab0de966772fd4319f460279a5daf520"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "62bfc94c20bc76b0313e65e197c369b5da9181666419e53893505ccba3b63f4e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "029301e7434ec71f8739cb6085702a676283c96d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "a56d7c97fb69b49ff5ae4ee61c9d1392a294fc38a1fb8d96e349a5901aa002ff"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0e152ad7844d9060b823f4f01d590121ea292a08"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "75bc36bf5498d0e263bcf37f782d856513db83f81dce133abb47cda4161f01f8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "736fa10b22445ff5d5b840706f3a381f65e60824"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "56624e0713d3e6af4e0b47c7a1e4d56a3cefdf235348aad082c38f7fda9b8e93"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "68d9cede270831028640dd15768bb3590c06699b"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "151b8f4b3e119992969c59b40b7ff7bf82a1da2efa968e773d67a82aa00322fe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.102+0/MUMPS_seq.v500.500.102.x86_64-w64-mingw32-libgfortran5.tar.gz"
