[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0eaf7d3b30ca279b8c8cb8d86808971e1f877690"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ef11f0cab1dc03ed1dfaeeee1e58d454067bc45902cfd23d317d3caf74b7ea57"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "cc0b42fc553016f1ea52636da38ad22dc1010dc7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b1ce89eebe255974457c149e0496264aff895e2219dd163d0bf590c0b8013657"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "fc5acb49ac5c914e89499d718f2dd1dfb35c23d2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c9d2d88945f169e0045a099e7635f091b1b4ebc6e8e11088b9adcf1b2f835723"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "8927fc3a14894e5dc96bd4051b66bcd3868ebf34"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "83b4489c983700f059f41a954dc5a6d32c5cea8287ce54d4137dca8e1030d1aa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "26a708bf45ce480dbc743c6237bf59f04c36c65d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a7e45363572d991b048cc710cf9d4baab36837e79bde31402b55279a6a61c669"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "46f956b368b1bfdfbf13f76d973bb0e38a2df323"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cddd0fe9c2f9c0da1409d5169c18f4c22a4227a61dc674ecdc88b031d6a47024"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c83955b0980a80fd15b14f681b390f75a48bb04a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bb2ee2cf2401a67e233978482272f68eeb934a6ace591816576bf8e0ca9bed0c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "dae28f048553c743bbeefae7269c31eec49e6afe"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "2b4e263aebe63b1a0abaece449ef3a4514b99e1665356cc13153482d40731ebb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "f94eb7f2da9de0a86374f60ca8882f0bf98330a4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f851b4dc1ff2e79c72a3e52986f129d09ac2c1db5524b2dbca19db9adea6d298"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2572ba1c08c1e0faf83839c8ed0bfb7b572993df"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0fdfe21ae60a7de9a2db872bab46cc1006d7124cf9d2bede47ff033db421186e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "3851d6c031ea02801fa20a0f287fd0d96217389e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "21e8c3a71082e2750b81dfa3363a36405f91c9ff646c696d74b927908e07e4d3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d125aa81e7daf317db8bcb3498f7659a99d3f27e"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "af87cc4dd2c653b52d72a86384fc51108f6cf506daddbf7b5fa9e815ab5d409c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "1ae5a800f8b7a02adeb0198bdb8571157b93e828"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f34f2e748a9cfd419a741519352103d57f95eca2d37d1b9689ec43a8baa833bc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7b294725be54d1eb89865dc9756b4fea9aad9e22"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e79de503dcdaf40f7c6ad65de38a9fc94324380cd204d36da63a247e904838e3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "1885e99c6d65be3796f05d685cc73f27023a14f9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "509d4e43f44300e19d4d3eb759f21926a83ec185012be2f22f515bf51418d175"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "85636c56ff20059d466f2c530b801398692be07f"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "e94a8a2efc1c4a8b904bee11627f691c5a3663eff94a6c769e639079091d361b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "1e306eaec1f1c31cfe72d5f12c8d3e84eb1ec3d8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "23f28bf4f558187e7f4d546843e51af4ff1c0432e4a9373a5cabda35358a6f47"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "ba3743d5cf5e2e47cda78e71963f03feba9ead60"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "db9189233720bb1c4c3de29ee5c6b2f4a742c55f842340a71da47e6edf9bcdc7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ace76a0f07db9e4ee3f8e6fcc5fd59a964216d8a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "debb72c43efd3efce5976fb30ba57e2dad8a5ae6261c2f37e5e54e1cd58e2382"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e8d6ddd2e1ad4a0bb62f0e03ec428a0ca5b0fa2e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "7c95682c64333285cf1d5fa2925bd0b21c917f02f307116ac3985e680a28c57d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c02d8483ae4a5f2ffc2f22b29d34e73d8a387fbd"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "4a8aced6f8575bbcf452a5ad437206c9b0015f664771fd56bf5b91f532fb1a24"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "976813f60fad750dff08241c804a2db2a16bcf4d"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "3e2c348c560fcab95c5900319f13ff251eefb58a5e1d2bf434409fea4aadf5b4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6726f4c46ab9dc9da82f1d07862fcf8b12421986"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "554abab4e26cddb33ce04de2171c04c04f48b866910ed87be2bea4a4c8dc5918"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b314997623d3fd7cd0719ab5b19bae08008f6d76"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c8c54fea6c8d995a6c2b1b81f497d6197d57c60012ecda7d8a43c48ec7160d67"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "73e95bb21ab21e5425d08af545d61c7a06b31f43"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9ed2d5cbefc4e181f9a37be079afabbff37da82d8e336b78f02aeaa6edf13975"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "fdae7656e3fbabec470520f578d98d56457af8b2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "30c246d97a5923b040c01d6ec18f105e6c348ec68ebb308dcd34e8fae9af4598"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4cf44f9eeed122b08b0754f68b7f4845faac79b3"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "b5d0cfd50b9da8fa537b4d314fbed0ea2be799e463979ba692fe05d7a31c3686"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "de0b84c775e7bbb45fc300bf417202a47db709e1"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "5524142eb24789c5212d44e9369bc38e7e2427fbe42b0d7d826121d529983c8b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "fd0bce80cc82bedea124479b36c0cd24d485803e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c87adc2d7ea167e931385c0638fc4cb7ff94a6f53690622a0fd1ed82f86e11fd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e045131f20ba1d0efd536f805dc535ec58ade00d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2240454e3f309196732b347bb166fdc52550b9f0c567e68876f88a0df1e9db6e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "f1b79741d6fedd9731b5a86edc2b867311fe51c3"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "b4c50734f683c709839a44232c25be721151a4d6a6c9552bba696875d9cda225"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c875e62beadc2bf503470b5ed2257033bbc3561d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f5b60be4827dd899c870c6f9ad9a3e3efe7408ac31aa59694a393e597c05e7a6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ad6a62b3499cacdf1e74d0d00d384116273bf535"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "183159546b60021168d7be95d2e031928553ff4e8342a282d2044a0144e05078"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "02292802072ab48fd56e123a81051ce9538c08fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8f335755356604195f3f5ba2c487a30675a2cfa5f0d862c5a50871d1e4729e4b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a1e7e1f4dcdd5ae88e152eb7a9b870258d79ba71"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "c09a2a9a8db56f7885190864e8dfe60da0f01524090369d6ea26bbf590b650e6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "d3f7fe085e091a24ebbe1007ee13c5c8aa11cd29"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "72888a7169a893054da3907eb7cddf1af3211dd25bd3e7ef1a272ee1caaaeaa6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "76552f3d459d72b13abded530a3be85a3b0fc5ff"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f994b151b691fde3f52c2f5adedd1bd667df3bc275a782a8724ebba69a5eca03"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "6a9da4bd99a28eb0a795d6a58d516ab64edd8455"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "20c02cd59d1eac8b7d732472cdd4401e422d95a9ee863686967523754d2bafe5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a16a16bc9e083bb2c21ee8ccd0526c3378b7e329"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "7932027ee827b39aa8575d40c882d1fac6161e682b10ff54c63f4c48e9af66d7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+2/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran3.tar.gz"
