[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0e3a6a4981d9c832532509d8d58ae69b398f9dbf"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "411ecc954fb91d6eac33e4a3c7610720d595a804b3eeeec039ad1c01e7760fc0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "8f07bfeb9fd758be339bb66197a7edbdd3d74f17"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a00148f1f06da37fc2933d4025040f2398913e0b2ab209dab75da21bf1eb0b39"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d6e6eed359ec6fe5b1a6d1d3ab1984f7b6f0be34"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ced7637edf36fb8c27da053e781449212d6b7988608969fd6795c18050ff7cbc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "72a7897b984b729b26a645f1349dd043a419918a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aebe468f43216ec119b66aae4e9ee0b5cc0e9a536810bd51779fc97ff8889cf0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "8c61487f75c8f33b4ed7edace5988382cc66186a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e2a25ed71a0a3ee9dc6c2ed1131f127d97a5bb43dc92ef368d63eb6afa94e5fa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "1d8c1443e187c1cfc5cf49bba52c206169230517"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ceef1f61bc17b2d58a214becd7ed40384ba245ac4987153009a99bf9a8908418"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d6059296e058213f0310e69a8efe9dcb1c39ae89"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "c1395bdd13c3db13676bcf16cfe2a05643156731e8f7eb2e8d2dece9100a9620"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1f7f87beb5cf5d26e5ebf97f371852777a3fcba"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dbb0d1253a08943b64195e49e963bed04d0d8f875f60a5f5078cc0c862d0ec4f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "902c601e005e3f2bf4216a8d216d94f2339f3ddc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4da54eace532e5a56c17f38278fc1de3180be1dc35adbeff94a4030ec876c571"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6fce73774073126694078c612985564c9d002461"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1eb3519154637241bb3b36a3adcde9fd2003ccf5274038fb05760eb1346a4bb0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "98eaf92647c050841a4fec45bad4784efd3e59c8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0de1c22f1a563f6207d32b7898c62837a7bb0f334e6134517dcb5009e2030fa3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1c4a91fe4ce0e0ebbcbb94a0f95888fcc722cf7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bb5fd535a0551c486397ba9670d7676e1c4d73419215e4a366030c6ffffe2673"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "65e49bb11915248a4246b0b2dd0917206bacb2bd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f5c5d2d111abc250e209e3cf919154288aac59b4f6fe3e682004a88199236189"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ef85a009107af749abf849726f3adc61c30cf75"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3150a6f508d48db2374a6101e2431e57436d3d37a43564542aa16e9437c7759e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e8d870a1aa31e6bec84e5386fa883caaa6c7a429"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9956e5deb970ef5784d3e19846836beacd5b0b8379829bce25ce1917006715ae"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41b3e18113e3c04271d9af0a408139db86883ca6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c7234aab2b68be3203eb22a808b020fbbea833987e710f7a0f82123c569795dd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c97f1c97de941807239a195cb1723693a48288f3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a1c37e0be4e0a6e3b2e506c5d67ad6fbfbb442228d70a73394ba4aae7f00d6ce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2e0724bc0fd006a1aecd331d2202ead4fbfc3b3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9bcb79ba070148f670ae91afd164a86b72599a24bc4556303d95c7a197971268"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "945749ad9925743959e45781b369014f5b769cbb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b8d035fb9422100a521eea6445a10181799ed1db077daeb2a05d51f8e8d28e71"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a6c1ba32ade8040298399b802b8a4dc584d29c55"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3c43c0fcf15789a4bd265c531a2987dabda9dff47633134d69ded890d3ef2e1e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0379e2c41c784112f02ceca633bcf287046dab30"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3385aa7cfa36af555b3345e9935df9cf8d2fae6d52bb83bc8cb718130030f89c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1b8fe155c298e192e4e11cfc758c301a29a82d74"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a303e1a5cad29eba55699a8b5f32591d0a5984d8948b2fae2b361e1dbf78a24b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4ef17e82078303672e0f7d85ce7e7e18c7d174ec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "298ecf75528cc5e726558fa6605ddef7b599673ce406705efa25d693be0d7718"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "032ca3cf137f9411cd7e0dac9ca4ba63f801f915"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d7f0e1373eb828180cb7b7a96d99b30dd848b2a80499cdb9210b2ff6dbcfb3f7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8cc15606b2e580f0ec4e4a406e61dd60d9f7735d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d598d6c356b23986115cedd081d6cfd9760864b8287a7e25ee1c41da49b842e0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8a727490b25813b6b692d539bd12ddc9b9ae6bcc"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "52b64c3e115a27c18d8d0c33b7fd99a0a556663ff6d87e24daeb1c0c3ca83085"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8c5d05f95bd58829489dd8e3d623b77fb017f203"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "140795224b5ad343fe88f71825c5a892430fcb24d216d9e82d6b19a6e35b14b2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1b62cdd06c4b56bd506003bde351bbb6c71cc03f"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "8b3dcf66eec5756d66d0f14e716f9640d182ddea6380e5b22b64f9ac05a0c8a5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "767c4694dace10f80f15bd90a243895e5c0049af"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cca7c54a569218f89f0a2d96b885faf1307f57c8fe7b0ef927eefff8b85ae0f9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "99adf9e780fa846f01e181e153b9a99ce9da32d6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "22faac19330efa5a295923bc094a6fcc12e67485c13faad211e8ca155ad8c4e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "23806d379b29a7922e1131ea8c558a1c9ca41ede"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e105c8858a7ada3be1fac50683412fe17a7a3915f13810fdaa46c69dec03b5e4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b21d79bf7ecc5a2d987afd4a86bb9c746dda18c4"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d1f81daba135a9f8924912f735d72a5f02783bc8649136e1c9973048524b1da8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "76c1a6b775d1662f7eb58a1ee3c406d6067c5458"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "6ff94964364060c926dcd551d8d920e24317ab16b91ce1e387fd80d92d01f64f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7de3e2ab0f5ae31e7f1ad0f94781c420bb26255f"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "0ed70fb443722fe87882a4379ca6d156806c2237ac695dd5583af36e85721ec8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b986f112a52a8b669cfa5a0e9a4d47e8c9ee5d60"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7a6207896f1745294bd4d5ca00830ae3cd974c8a4a6fd2da3f32d1f81153254f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a1ceb9cdfeaa75babac225ae853477a570cfd86b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ae227d037b5e06d0c0e286efca43be067f1ebcdcb1197393d7ae8c070c07ff0a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4e96eef1858e16b3b280a08967ddc9814bbc8cfe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dea54ebf8af5baafec80d2c1cffc6ccac348ac13e4f7ac848e0999685927af4c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a378153b9b755e4e1c73dc5353137fa29fd35419"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6ef17c6fa37df5513662ede415f18ecddb845c6e3a41dbb74ae6fc4118c9b115"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8a9a4bcf6283c52576b3b38e071bb0b339f14ed6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "799636f92c915636d02f3a1bbe0f450910905bf1d8a042af5f46d83aaf7ebe04"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1f710e3e05425e4cb63d5c46e86b23edadcc997f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "eadae37e99e488c82faf96f31561a42d6f70c112e940e76d36ea22bb3d384d0f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4faf83a904f37bf42fe41f573880105c76c45099"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "56f35187371055b86b7992df0bf2942514e03a8d7837545cd02d388347a242e6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5c333ec37114600fdc8f31f59c892779d06bbf90"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "edca8f4de4d4e1f418e59c2bafb6920417620d2f5ed99db448e3c0f023d7cd35"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "120d88477afd5add870b01a1325f65f003dd6a68"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "689fc4de0b3af6770bdc5f2e1373a6da7052d544677f0b396eb675b28d757092"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "df1fd804072f72bf3c2c4d783e8f14952a350096"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "311053364c415774562f73ba07033b3b9a442c16994486a6143d1b63d9689bba"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "563be75f375c12b82b4ee28d965df3bca63701e4"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "9ea1a88ae9694632908a64006ca5c50fb2f5fb9e87a19051dab81cca45ee11bc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "98927254d23bc17fe0266597a29983518da16ba5"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "de2e752e3bba65cdb80b16a248bf6f75ecab9a79a9abd5579f38bd4730c27f6e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.800.0+0/MUMPS_seq.v500.800.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
