[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d4b1312067b13d701112e587c514952c66e4a107"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d58f13592e32c8527b07f397faba7fbf8540fcc781320d1842abf0675b52c1d6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d7986fba63447366e3ff0b2269c73e8cb1d28d9a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "58c614b4bb8ee4965411d4f61ad65e27cf2232955918edf254d824ec7305c728"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "1bcca4b30899de3b1f70f504ca9b6aefe5c84e9c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "00e79b40435b1d172b7423d33c7b71c738043f4f6401d433c1b734bcc4cbaa4a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "995b8769beaf7637fb61da3b23473e3ca286d71a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1dd7f303611fb2a27c8f5f4723d003a56d9ba2d3069fddf3483184c13ff47000"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "6b8f7a7863f6807a8ecb348c0f9d6644c894064d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ca4187115b627928be00142b245d8a008b39ec79f718f8ceb172f9d83140588f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "3a1f616364ee1c2dc0ec6be66363944c12a1a365"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "728187f945b6ed235970f1dc868fe85a051b1b62d4ea25fa077601900ec9446d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ecc25c9d4d7cf9b00dd999535262cf31052d9c4a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1b520bd62ec2b85205fba8ff5f7073a6fbb5a9305073ff46390d7ee12f2149d2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "725d5bc346e87b5549a87534af343947e4f261c0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "eb663b4798f6067f033ea224414a90ba17f91ee5f5fddaa873d84827cb9a7041"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf3a5f0caf7b302be7cabf0cdaef920be3534507"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5c4721153748bb89cb6c8123d13922247f0cd23e51f8293edf9b57977fdc6278"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcc89f924a63239727c58240f09ff45d807b46d8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1907f8d65c1af82da031aae6266146f8fc80d0785922c3987c9872101356bb73"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dc52e957d6bb916220e985a97ee037b7a0630361"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0c719be55c69c8f96a164d27c296b3e7c8bf9784ab85eee13944e57561257c60"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75e4dadd3c3cbc3f45179387e81afe8206662ee6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4bf4cc76ac56a1ec7f9e5c373ee448291d0154d196b677f943db1e7fa1a7a5f3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24cc9e8ffb4b198e5b12af4f3705abecf0b58620"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ce7dca2a648699f61d9e9118aa6912e37e575d25bdb7ad2bfc07ba257c42323d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6de32e65c66f37275997d02f048184f294d43ac3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3d6d25c8d5acd447846c8858ad9b63309e606b90d66c3eeaf1ceaf2b7b0a4848"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78e55363eb4cefa336a5f2346309e695b11a29ae"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8e0c79e22906a7d6f026c446f82d3eb2e32fe043e72b827fda55f5b05c48850d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a9edf437b5c163ec5bf004c0f34df48b328d7e3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "41609a088a035ce1598c2d885e5570765d133552f2a1ca85d9c97ca2300e6ff0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a332c89bb9ecd712dcc0055d48cb579bc5f2a2d2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "956e4ce7dd8f5485596b496a70c2a39824bc6710bc04aad0e71ac52775d1ddd9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3e2b1c8fa20ca1097b52ec5fcceb06bf6c721d1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6a759b3ee0cc9ec28ddfb704f4dcab5fc7ae94bee6263d596ca581050580df6a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6975cedb10fc15015afc5e83a517c24760a9a2d7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d4e11050493f0a23a613154ed35e76147548ce8c86a67c2fe503d391c7c09bac"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "97b9e0849924964e92fb6baf375ca47bc6c839ca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3e37e8d41fcb3e4bac12441bba11dd35beab76c29bc8ee6fd34f760b132c545b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "691131738586b404f1674fa6653255c5d1054fde"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a52104c6dea647543d8455768adadca43ec43dcebcccc0978715d7c2892e6f77"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5d7a8b231a1b93425aaa3d05494b8c7cd2c1936d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6dc8c0b1170747fbea3457b2957bb2534d165ed98ec4a8ed29db02aad1fcca78"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "d1d6fa905576e9782df7fa21454ac5cf38ef59ca"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aad0834421a0a617873085a6a5be32882448e1c1665beb8818e7ed1e468077df"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1e5b51faa32e6304c9aee87a9a14da854392b0c7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "789195a8d9ba199af8e5ba71b6399270cecbfe7e78abece6fa090e69ff2ace4b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5ca84a3ef960f433af88874e889eba938b0744e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fb7e48178fbbd961a114c8d7f85dd96e68fb599803e04cbd6e5bce47e211e13d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "99b65cbe5fe354ccc05553475269f01090180631"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "93eccb3f392722a8bde2a2f7ff27b11a3c23a67eddd409bb60e6a57aaefbcf97"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "130ce2bc697f727aa49c0d7d124d2f0125fb515d"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "4931185d6f489da86bc51c1de68482e8cd310fd5d72357beef49679218805e57"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "3a036722db3f9e86c9f6fcf9f1f5c1a85388a857"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "d0b724e259bd44bda2922df4f00d2fc9a5c5b99c89f23f1eb2b7d885c540bd2e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "c29ee67f74784cd7feef112fe738ec5980675ff0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0949f37877c81f579e0369316fb4f1cb847a09e00bbac31f4fb9f14152ae074c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "76aed3752c96884d1148e13bcfd8bec1328107cc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "389f0a62ba4dc68d7e7e1330e7d780444d5f68fa530bca14ccdbaa3dafa72f10"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "9d47e35dba018bf334ef698b319809c389dfd612"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "650571ceee3ba83ce10d6f68b3101be152b1ee789d3e699320267c6be232fec3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4a6a69b9da118b9c7c867306db3408f4c8ff5783"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "8eccc8532cd45cab24401e034e1ebb4f21b2291479970b669b1373268c3ec724"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cef22b09e17847ca8750bec98b458bd363a16502"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "fff1397f1f3ac8e4a6bb83591525dad515fc6ce5f6663f617702f9d899190ca2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "95e58a15fc9a67cfd2fb40b114622b7f62e04663"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "96af7542130d0bd4f4fc627a3beb74e7e2442a43a39e364d50fc23a584aeae02"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5f8f06517035951ff03b1ab6897562db7a5fae3a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "04b0031d5c1957c10c90631250033b9d3f772c2e786fd67b6a4c5aabd2f672c5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "26d9e0238cacb264b458b677f637ebfbe01bb718"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9c998368ead0586d467e4d4a32faedd41dd53a811a45c4c471bf9e3db81bb2d3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "90035b569c5aa9967c104828a435f30ec3a6950e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "715c713b49097c91675a6036772c046392e43bfca2c54316762fa35d2015305b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7f3a080e24f156b47416b1140aa241cddfcb938a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "19b0a9c1126610e3eb954799e0ac7a94436308c233d29e74b5f28310341b0764"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3f1a3eb8010fd64e47fb7d2c74f3c0e5ae470aad"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5e56ea1e6d96a36238e573f0cca4dd60e999b1c19b8f174ab87e22efb280c507"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "059d520b1e9bfc79926478f30d7fe0045b8d8372"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "20a83386aa89256454148ee2388d442dbe33f150cbaebfad0cc06ca1e7f75988"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "390dd482c5682f3674aaefaa22cfa9d4f605e3c2"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "6d3414ad5556d9cf14c24a038c380c116c77f5d601a401a51fe3b85631d4ca8a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a5bb1d1c085f92572d367dc311033afb6d48a3af"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "c54dd8d01f7bc0480aedcc10d6eaa4f6cd9fa5cf6c6629aa5d8839f81a35ee72"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8580d57432c21baef97b09cfcd12666d88d8ba8a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "2cbd141cdbd3a4b10fa7392b03afd3d90f013b5b669ee6c87d31cc0fc72bcdca"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "00b3eb9a331130ab340177ed34871eeceb102b8d"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0bf8eb293f9305379ef9051988b00ad345cf8d1886b7b142f30f15f6c01a3751"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2604091e89fb1575b317ca7ae8b6e04ef471a6f3"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "2223f7fcf15e38e9fc42c3f5e37a90a061334f1d5ee443dcc234a20776c005c0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "45e5e7070f8da7d9e70020f0362ec545ea4420b5"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "26256099556b3164490105725fc51140b16c6b88fbc2cba7ae64068bec6a95ce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.500.100+0/MUMPS_seq.v500.500.100.x86_64-w64-mingw32-libgfortran5.tar.gz"
