[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "120b3c0a9503da85ae32a4486319712314100c3c"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "3ec4b96085417ab77238da4ebcd47ddc98b0ec1b53f460eb749d2dac5d62d61f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "856abd466744acefdd3909333e299221c3353f8f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9ff3ebcf04dc4f4d9f45a73b7b7d9d1ab7ff3dd97f78cf0e23a81f225f08c9dd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0d2dabc00f032e9f1d8361696f5cc13e106d0f92"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f34789b2db735346d37e8d92a55f1c7525df6c056fbe5fc63e2785fdb3c706d0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e6eeb5ec36e4bd78b07289860f9187af46027051"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "64b65f8d3c0840270049344781be972ef28c19101212bd82d475f5b7df7af642"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "367e7d6a5c75846170ae827e001d66ee79186e10"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4831dfb5acedfca117feb2fd642c5894d710c6a6e3c728e9f234d81c422d632b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ffe9a7b80a66670e02f7357165d7bf70672c0b5d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "08c843f18c09b16885dc7202f8f608f1f135f5a5c530655547856eb9907bc201"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0b8e048e3de45169894da8b0c0195de9bce5449c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "eb13fa281e0503321ce7d0b9a20554a9d409b7f591a92f55c153b21efa1a01ce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7dc8f9a7a68e4faa80e16bd81a9e45cf74abf7b2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0826633cba48f20e226b918753679feaf1870b868fbdfb7560933303fdad5810"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a91293c77e4aa63b0af23a271b8da1a431dbeb2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "62b01f5eb89aa710859496737d430bd9a3c67c24687f26f83e044893cf465caa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5033789f9a62b9b6b9a6f66430c9b338fe5ff115"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8433b9f27024eb7ded9a82dbe3d95debdffe42c4b96acf72f468c7c75b058374"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f651dc780204460247ade3d7f553e84b4718407"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "95f903ef9058e85f4463f20e530d5a948364ad7452b03d286d3484d50f583b3f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6fc414a02858323cb4c1307193d869b393a3265a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7d7cabca0532d5672b282e84814e98e42119e81b2ca7e64ab5d61732094cb2ce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca4cd7c9839fb63e6a538b868c4f0ba6eb908aca"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "15fe62807aaf01a339e065bcfdf0db47feab1d78c8da984622e407bde9ea2ae2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bea7c3fa6c25b4ad0d53fc0cc8cbc6ab191c451"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a6d92423fbad69385a0dbac7ceddbf2dc49b7a4c7f5a1185b07f0032287eafc2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd43e1c193f25fc07fce088ae022e19149d30080"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aaff4b089c07200d937c199411e7ffd53df677be2ef74592e315f47020064a31"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d67a02a6f8e1cb72ee36c528f5be6bbc8eeefa9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b4f51630b2abcffe3f20c58198a8904196542b1257e9f03d22510e865913fcc4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e347a18d90ada242c111eb0ac5496d5acb7d1073"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cef9f6e83edf25d5b801a18d64b53bc77b2b8ddf109ca009c8d1ca2833a02a18"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e56c8d01feef00c20f0d1c57a04349c3f3544747"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cc411a19f45e77e0928813286b5965e05f93a15e32d987b4c109203bca80d2e3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e49447f096b1f1dc0df706fd5d3815c01fedeb9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "65ca126acb5b6ca6ac3abfd0fa1784e92a8280328a057a9603ffe1b088858c7b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "237bcaf3f7f2b88bee29493d4d9eb2379ea63c9d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "735cd4e24f8a748fb6f7997d4e3e3107f39b8fe00315de61f420bd2ec983da57"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a74535713c63c96cda954941282bf17d45518048"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "99cf2bde18dfb9a73fdce0d959589aa970cacbfbcf34252dd164968a4603f223"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "9c3837d3a8c0ab4fb2bf13cbc97097047946ab03"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "db0ed962bf970def4c7ecd93c3643f6b9aadd3896af4cf04cb366c4d7e1d846b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "755bb845bb6b7ac9d9df3b9deb9d51ac918996e6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7dfdb16a55e540f57fc9fe45b7e85b29a1944a6108d9ed875367df5706c5d9c3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "fac0cbc7921b909c3543f79be2d45d320fe5d621"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0a5eaee5126f93538e2f30e7399c96ca64f9877ad9f0ed6dff692674a4f960d1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5f71066ff2eed0567e45c87e61130c4734e0dfad"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "824c353bf10dc36061ea406a4bbc0dfb584ad3db32e91e09fdea9dec8a0c82a7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "50d9b20a2e7593ee656fd8b8bf948b325476870d"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "512210ab6c12e8e57e055b1a52c5df3320d1c68c6b95067b6d450a129c08f129"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "175ba2a7e9750a7b46cc9057474f3e989107a38b"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "09d381ee5c65e08a5230b1808939b7ff4c06ad05326db13e011bf6c20d299d71"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e18dd8669b050841f3bde9771fb445b3064fbba9"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "628e37094fae07057d3124a491caf5bffb8c40b1116a17cec3aa6577ad6e723f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "5052479bdfbcd11d7cb3d838ee49e8b46e86ec27"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f85a9bd7337fbd290c2fd14789063fa418c4e8a60fa6a3307859252b4c51bbe5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "d444eb050c2bbfc256f160df396f99baafbd4ff7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "11a2727e66bea418cf5bd310376bdaf1e3c48be6d0abc5ba68503f65c4ccbd35"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "4784e0345b2aa0b8a897a4bf6b77582905312487"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a19ead83b95d14328a7bc36e0dbfaa64eeb24e04b55a464e22c8f8763a698568"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d479d4bbafba75ca805f36ce145654ad35067a6f"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "e5c98be104d65e5222210e8debed9b908298d647357b9082ee62b1fb05a2767e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "17c35aa4fad9ce053cdd88e2176c948a0669e5f3"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "ace41f5e05c5acc305944e4e65e8a17a5c52c544b1fba19a5da24da7c244a8aa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "dab0a978af2401d86813ea0555fbe5ab477b03d6"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "544eb76dbeb0074426fa8e587f1ad34048b5132a891f25b7ecc7749d75fc0a64"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f679a8735ec35453e69ff6c0bbd45e1fc2f0df22"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cd1c55ae848b80723997abc438f0d99fe63c99bef2acc32c3db582b1fa19fafb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2fd569237e79364e377b20373015bd321bac21a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "75a0db333ade83fc8305efbdeeed31c203b032ee59286fdb975c059167343f0e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1530f5dbcef417551d0765a8b4c2924a1c16d1bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "077b61fcc713462d7e40946b8f23a9a426cae5e34e2d5d87c1451abdc25ed52c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "836b6d4d042190b563a782ac4cb7f0a58b4d0fea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "67094765c8c69af0d7406ae381f612f9173d6862baccad38255cf7bd945b32e7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ad7fe399a021179a58ec510b53fd73b964b00921"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2ad03cc29bc38367241b56d9f477d4500559bb3d928c14af1ddbe7028b0efbb4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "056dc52f41656651083a0a7a46b9d87e9ada7ff9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dee9910a37f58b91081f53d603c7c1ea8f0e541d5f7166a573027365d6019a95"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b4e2e8b4914c10517965f6b7b731faa33a679a0a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "d87ef78037264520336c076070cf971bd04b0bf385bbf0a7790c50dd0acc30be"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "52d377fc5dbead4d74599498ff223246d5b2cfd2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "fc4fd0c4d50c3eabe5bf61f818458f9fd8c0890c3966ea2b2811996357ee326c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9f1058c7d358272c3c4d6ab0f5f984cb7138d7b9"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "da061dd0176a0e9af8232cba01e39339037ce3374a14bcf474a249b5371a7726"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "38a45afc2103451053acb6a44449922b9f644632"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "04df4c26d20ebdd6a1a3750bc0a76aa0db9f06ac1781f5322e398e0818f4c6e1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6735537a23f936a0ca0c1af68c853beb6bf752ec"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "6bfbbfeef9c0538b0705ec9a16d3ca3ef1f942ea3cfb7dcacf3843f13a47eebb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bfb5d4bc307402b7bfc84ea5adfa97caa2a48c96"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ef16906acd6974e1dca400c361e57e0299792e4fa709cea23e1d5b39169c31e5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.200+0/MUMPS_seq.v500.600.200.x86_64-w64-mingw32-libgfortran5.tar.gz"
