[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c5f66bb0bbdc4c8bf1e3aff36a654e2cab3747d5"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "df8b23749fcea81328fa324958bd9562832acf0da3610c82b91c0c406bff8931"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "cfcd4ddea0f5f8dff234ac61fad9addc7e74cac4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "14663326ec8dbfa9676b0ab2cd019e96b5c65e3a04101484f9773a0e0cc9f266"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "f132c3c216fd873a56ccc9688d04169b224352d4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0ae8e3fa4da3b22bdeef312f5846a8a2cf9f64decb52c56089284f3ee8b05c10"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e4fd474fc9a074b69d63b7b8bb8fbde15fa08a6e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e4965cda13278894b4b7cf9355268dc98ca47414ca0c8baafb74fbf0f4167656"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ef425a72b65b095b61356dea1fc932deaf14fd45"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dd945aaa579dd38e465d305e83226d3d9feeadd137a352123ae789f137ad8f6f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "b3c52477795181e19716624d711970b031df116d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ff1b28648cae3460340a7d48eb1ad72696c4cf0dda128e9acf8d706b1868ad75"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e20c35126a7f1fa37863467810934313158d0905"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ce5ed9aba577fe44215dbdd6b74543575456f9bde232cda50c402d27bce4ce0c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd3548d1f4119053db9e775e1bfaddec29a29917"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3dd11d331d632dba3c5b157c15d82f92742b53397223783015453a6cf6be4aa6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7905cc181238b990150168833782772d76580d93"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3bb7b230aeee3361b4c0ccfc2e908a5bda366bc457eaff66d5e983b26f1520d4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01e16eb79496bcdfd3a021fc9211d1d091a50eb1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d95892bc257b1b3791218e35d1d2db3163c581099eca3832241bfbc465cbd710"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f40c1e1c061f64c765c6277ddf25575ad2b58a0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "001e4a26998e707f9122791f1f227e321c2f0ff19ac80fc9247f6e150adcd122"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff993cadbe89b1c9f26d902268e5f60073340f14"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7c6d7b504cdae572669bf3c8cf891b1401d61f8861856855c97d7ba6b86f4c3e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d60c10768d5ca7e3ca2f26c0a3501a107c7ab478"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7396ec111f5dbffd2902b2c18761e272136312dd2c1e1f9942703759f95b2157"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a192ea3517a9bfb085e2f4d3a562ddc3e7b852b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "87f7ef9b0ebb9c3dd32866bf894ed3fecd80f94b3e2414b522b3fe8e5004e76a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5348500e00682b272ebbdc412a7b54fc6afe0310"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a94b87fbd310a3f3320a6fe241edd79b0212e77d90bc50c02b8816e4d05347b5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e876002233c3d99009dd9882d93f01cb51e22b03"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e22221d58f8b2a2feb58a40b1f93ea2c3628810f89a6055083c09c2abbc2c4e4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bb783848501c683639052cb89628076e57630c0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a12aba4ffc2292a0e9b230b7e4b7e7334359401e389940d979edcdf0c9dab9a1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a204ed05b858b735383190f76714f257f4c49062"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e154e415859c997a91605504fe01474a64f8cffe16752a056dd9318a57d12160"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc2010cd6d7833795f37acf8c5dd3b95a8b57328"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "678755f4b52e476e2d4597dd59086bd1f4a4ed8ed4efe45a108241d9012ade66"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4d097a933b5e6abd4d47c483d4d5ffaf866b0e33"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dec361592b757ce4522115a26cd8c9e6bc5812b94060af8029dedd86afa43e3c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "c3298c625c84ce76640ed0b2bc1a0a7e16a07679"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a882c94412515b31f50e71b2324e87d1c2495e6dc32ae585dc1b52ba9701ff27"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "89509a0d6e6491e0b9fa856ac2b0f0b05020b074"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6500449a41d88ed0d962cd7ed42fe988c9c7d5326935b924be6ddf2f763bf374"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "68414e57b67a913ffb866c3db2b044c6ff5660d3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f2eba10497e86217d5f0a76613f9c469bb8e777f448a50a50940660fc7a747cd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "6f961ea192fb3f74d56acc0e0dac7c151bb13af4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "393ef1d38d8f15ae47cfb44c982a9801a150ab7b6250af4435e49eb15c1d952e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "613a190ca26e0700a60515aafa68fc6c63bf1cf6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a9840b47f4bb97ef73be1a460bbdf647eaa5877f520ccff271a1b7031e990abd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "e153c61139b898c8e9edd92da6a9390095b85f75"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "e211a3e2ee62a0a3f6c014c32b06ee7d15b7332cef2f98b940f80ec6ee174338"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8d37e8d0553a2a90f334662bb9522ac5fd2b4511"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "92602df9ccfe999d3db5cab4e8254537c952593359318de3db317985fce725c7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "9d45eda600d889b4ed4c3b79a9d13c7bc9a4fd60"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "56b6ab60e5a054813a6e32baefcf0c8bca2af9ebc6cb04a965be1f6e1dd67687"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "073bcf62a54f2cba9b9ab51ae097189503925ab7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1a0101e3044457c2dfaac07f99e72fe5d749c994327f6e5142fbeb410d2e1e2f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "e86e2fc8a0f78e41f0dea61b7b70f9d9af5fb6c8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "aca832aee13fda03549086831f70f48f444d44eefbddd677db14c21683d6e0e3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "f838a19ea4c8b8a6049dd7974f391d2aad7e5a24"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "92c21111e29f4a37032b89eb81b57df770fd2d4a49fc0b87424a9cf54d381a27"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c706dba2a533d5d34c24f48856802f81b78fe1f0"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "79f49e90beda26279bd2e6a115d65d575fcdc598820ac9e45e812d392450a5e3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bc44f5c0bad5220e1daa4ca2ccc64a926a851b12"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "a99bf1620576c6823af147f75d1438ec2195baec01b9069a3153fbdf5b0526d5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0a50a4b2e345730b5f4681a30ba2feaff51cbee5"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "bc0d65a18ad8c2e7f94268d928f0f916ceca7193fa266f6a646915b9d37cd7b6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f5b97608338b4074d4097ddc564aea096777ab54"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "df5c85d66ac375e1c21e0842c9e679a6cd6ca03182d1e88af1cd25a262fb07cc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "59d8e99a8b37554f46267306567876944304ba2c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "74379fad80de9a1e1d0d954b8c2f878173730bf78fda6461c6d1528dbcfe0e7c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "385a8564d3494d56902a5b24b0a3304c5c9fa35e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c5a6bb8f94251af051703cc2cf34ff6420af0088f29e97b43cb86f6cd9016cca"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8bae13d871f9aabb022cd19ef0aca35debb4cc59"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9baa04f592d0425fce7bfff4606fa3713aec54389ed8762b4f90cac46dfdd4f3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2cc44e6b7d41b2f5bd33605247303e3cadb38148"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8420c36ef7d4a4df32815655ca0e6e4784bc0a4439e5a0df48c7ed0526de3ecc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "fb68efd3e9eb4507e3afa32e5902ebfa0aa05d63"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "78855c0fa3aa38b625b14e489c57d86ab84bbbc4305b0128fdf5e0d030fb2143"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5e425202bbc341a77a064a14a08afa912189d346"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "06f7ae9f9fca10a802b52cdf10251d9770ed11419edc9edc55bf8387376b7467"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "14f6811c9ea3835956ba6e195f8d93b3727aab84"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "b988e502ae753c0b9ecdb956b018c40edb91ed8100a6a81e9234665cff7ad3d4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "edb6e078a8a2430f6b18140c0a9c3764ecac2552"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "a86b0d862f2b79dbda3f4468ace8335677f779f676bbc9b48dad1da19db13572"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9182c375e221c3355e3a5ad58922d2d7aab28fd9"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "563919f4e307d1457bd0ad18cac19b3c522f77730b8e8f0e8e90c96e5a39ea15"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5410382372cf7c93457528c142de7b391fd19275"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "fd95bddc72229a80720d682173e5506c20374973d79a60ae5e9cfbf9ce5b2a40"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "79f114c5ca164fa0f6733b00688193cfabfa242d"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a909109529fcdd9c184b67042177ac30b0074ef6d949a0b2ed209fbb719f910c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.400.100+0/MUMPS_seq.v500.400.100.x86_64-w64-mingw32-libgfortran5.tar.gz"
