[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a22a2d22c35f5c2d5b024ba198075a9a57ecab27"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f4e5c55900a7c49948632a0c8400dc7d3b102312d826fc170beb229d5c277e30"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "2e0313342b342a03e6d731a1299072f3217680db"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e160585f290fdbca5d582609aef0e16bec20e0f532104498d46832c9f89574c1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "826b21767224caddb39d3724c44e3abe7c7c9ec7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bc2d610101d739441a06bef046c8f6f2b15f5f15daed35c2f61313e498e52119"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "8f16c0130f8bb69929bd0d791150f0215673a66e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "84d58bf14193548f86cc2bea538274f9e2d359c9fba6aa634d7269fcf63b08f1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "be8fea7263006ac46badd26eb29e768b934582e8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2a44d709fb32baa664b88c0809072a4e60b4008ec1884b56305ff81299d15563"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0fe165dbc7e0f38e3e3586e869998c503f72c643"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1ff5d0a615e74c1a81c163965311b66e2ce18c758dd2058ddcff360cde202bdd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "d3a0731d2b78746193e409294c6556dba6345ed8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "5a3040bd5067f6e3493b8a82d0bb0a84837db4a80efb17b33f7ac7659f2dfd4e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2c32e11b790389406d8ce998dc7a719a73e2e483"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "993a67b8c5f13b325ec18dfcb871f04efe8a013cc6e1a0f601ed84344d1b8b85"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "e50f97d40e9a1c4226d5b827d9b350f563673450"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fcb35b1cef9e99173ea7d52664fc3bbee17bd561d8115f3fc312079e62efef73"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0eef5f3bda75f59898a7dce52c4e933b60c8d7f8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9cc134b3bf728f1b4c2936c7e5146741dd5fd42f7c684a17fbb66ad4272471e2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "0484fd295e38d79907d8cf26db4a1b29b38eb354"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "0631a8c9ad4191a858c7d7eab3a6b0335dd700edf2ef9cca97780937a682c81a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cf9077258477ec231dac637301664c9387b7c286"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "02e8f41be90840bb9774079f78ea8e9cd19909808bba29a631b9b32ba9546aec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "d37685afeb0debb29feb1cade5835148c04bb39f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "da93c7b4f8e179ab2f847f117be46e92ea819f79ebdd4d7b71c4221df11ba544"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "a0e6689401ac31cf73ab3c22048075ebaeb182b6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9c019d312b561708b45bfbf81480d45d98c67305c09e1bd5bfcb30017e1534c7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "45175abfa1d3ad80c61d0328cc06ad1abb347e4a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b9bffd375b9d7aa0366995bd76efafeae96a79d193fd54cf43b3c0a4bc966e39"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "10bd67aedb195e5df41f697594f83a2484f279f4"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "b2e6bb855cc39f0a4d2b8113f28fdcb2fbf09a605b06f4ccea830fbc3c4acf2e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d2b45a4ff0142187472d1d7a43dfeb7667f31097"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "353d7a3bdfa1d385af3e9f3864f866cc731519c7df398f44f0c465b9fbc6670b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "1c04e77578b81ae4d0a62f53b946080e3d0ba563"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d750b54d7c581178645906f9bd55b4c1706414e896832801e2a333d386286a79"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "79c23633829b41acbf45df23c0e0b3b5046fe1ca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "36aee300f39d19e88b64be049c45dcab2dac9965cd9ccc23f80753f5e6bc1a6d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "609e7867c6823b84dcef5f30f7b42fd409579982"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "d5d17c06cddfa715d4b2dd3132b7b76fbb771602bc526e775eb6956c9529942d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5635250fc14d79c77ae7e2049c8601c4882f16e7"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "03452a3162d19181d1e9d79cce7cfe4a0cce6b526cd7c4a254bb3fe1d2ac91cf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "530e2ec8ed33481644c264279d09bbdb7ee34f0f"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "c186f59fafc7fbf28a47fce40d88994aec7c5a90832dbb57f4de4f07c6b163c6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "df901ddf22c95810634c964f80a527db22e90bcd"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "b558e207b9ff08fb4520d9bf509d091b59e37682d7ee881234402f0f1a6a7a0d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "798d1ddee3eb62377a3ec690742cb6ac763c1c8d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e319ca0e5fb85d4befb5129db2d0501e409cec391bc661014065ba11c1025750"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "865279b7dcff47a469a0f02eec4ba3f73682bc46"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "705c4f21066731c6db10cec26242e7581c173e6d30bcef6bb4de7406380d3729"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "8e08e384fbfb1d6a46dbd6a6c3979dc4cceb7178"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b33908ee7eddee4b2c05f1582dfab09829dd7e22857d8fd99f3d23eaa8636ef7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a3d1dcebeda43774960914e33fb83e46bbbfbd47"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "aad43f240f77336d3e1271f484eb2db687e1812e60987338cb9f048ad7b38c9d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "fb949b507a629ef246d3e1599d43ee8e8a72222f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "5de5ed864c464107edaa2b197a38c0b273db16dc3574437b3ff3d397c04f8a02"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ab86d48dc5e782d98969849cf6bbc0d8d84f3299"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "27cefc8cc7ff77dd49a7d8ce352fed7d9b368177398f8caf7c5317a4c5e89da5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "9659ba31fa85dd5b0c1b2ee309a53824ec53dacd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c1bffee2f09ee677f7dd1083ed16f5ba79258edd0e66b16b0086f43ec941f1af"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0d4974825600ba65fa4c1f9938f898937c8c30ea"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "a7b0a6ac2209f98b393b6c1bd9079992f2c2ff4b5d1fe8b5a18ccf1c6a36d3d9"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "81d482e6fc9d708cb2ba2986a7ed1b2a1eb79767"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e29046da7a6de6712fd858bb51b4e83710f5bf6dc8381e4b30e32e696634ec28"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "0751174b62523d507bd2fc3127985345edf2afba"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "091a7b8a66c971792c97aa883258bd4b5d73cb271f4cf7ead72d699732c5f37e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a5264e573ec41e0d9edf473fcd17e46593dfac7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2362e52a92d268904827247d316fabee7b2876e0bd5350fbb73d79c58fc572cd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "879fd7c571c1abf8240336350cf53c0900b748f4"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "76463b741986e3cc1053c2a89ec4ac6254e940e4755cc07983eef3155b2d0dce"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "36e55b85205311458243df7d766559f2454fcb95"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "40ecd6e639db5603816ff8121f65312ac2ee2a9ecccf0ef5e26e5aa74c1cf389"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "225fa29c1b7d3d62e6360c85368a33c8db62b6bd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4e0e0f82a2dda59171f02ddd60640c89fbabb8c253adfa300d40d3814f8ed1af"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
git-tree-sha1 = "ef5c58c2a1b81d1f538afd972d98dcb9831558e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1be13d38dcb71c40be0d93f1bafffd027926e013efa3cc634d839d2fd0eb2cdf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "25900a72044a27daa2e5c71920b90c0cc0ac5c00"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d0b640e5de2e3f83e9f60dfd12875537ff570365828ece271d3a2311b8cc8938"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+1/MUMPS_seq.v5.2.1.x86_64-apple-darwin14-libgfortran3.tar.gz"
