[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "53c7f60a553c2421ca0c4a0fe607abe9ab32bc86"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "80ea26e3dbd5724ab45a0682bb2e3b648113935c59cef17fcdf5fe2b5a98c9db"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "31e1e1e02989036e025325c9fd8174f5adce181b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ef451f3584a46f9fd8026aec0268e39c1498ca219e29a0feeb873bee412e6a12"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "155b2ccc7b29843fb3112efc5b44e47a865ea992"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c2763608fa0ff0e93f6859743bf376a2e27b9ec2774c64e56fc8197de2d2cd54"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "a1ef286a42ff0ac0756f25acb183ece9d6446e9c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d757d88f054a1dfcaa0d4ee04a9adae6a988d16ad1fab55c908475a1c20e9c90"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "8ed7baba1f1211cef95a33a5c56a6a81d998143e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "38155e87439b1e4f65ad2966eecea8fb5bd64ed79cd2b6512b00e2ab80e2003e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "c9df9161fb117149e5eb2b25ac84c45c1f6fbc89"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2ab75223478f6a5f4d3f75bccb19d2f4988b09470dce293136c6a6eb899d623b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a9ccad0c46c14225bfe1e0b383fffdf4050cd53"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "463799decad9f7311b4ec6301fcc77f7be6386b72693d5f2710fad294cc93ec1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92a8c98505341f8f281e75d979b88a77dc568c10"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "12def763b5e13bab89b6683f6352f225b2858bbb9ac43830cf84915182f97ecf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e82a73bf4a8f2caaf8d8918ad92cba216a9b9097"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cf4cc3be9d813d8af5972f007ab0a78cf60e7a2035e49d9f8b710f1d8ebb4fbc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f45511fa5f5d321849efa5e641e872a1749d1278"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "07af7b65c596bc74ab31dd9d2c7fb1f27b38a288ba5052684d97e8a8548d9726"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72dfd5b93f85d6a7c3dc51661250c5e7a47d286d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3534d2bb5b9c5d75439f34e60fe6b527e73abd8cecbaf4ab8576c14dd8acbb8a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce17b4e19f90e0ca870c1935c7b23e912c45be44"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ae1fbf65aaa00ff61ac09277fa526d48ed109b85bf2cd0b43eea3fa854b02f78"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "6d110ddd883b1db400c180270e9a28d2a30b285b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fa709c8813be47b35ba632f559a25b19f446e8d1aba40ffb93f1798569e2bd41"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "59860417e68c126e2362c5054944133aa2f38864"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e78fef51c426026515d439c8be517e9acb483c22f2631085f417f4a2cbfad42f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "39267ccc0278c0972e085386ee68ea497465257e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "bc5a6253edff023916632f4d8fa0d228868a4d3226fdfa68c265644656f4de7e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4a847a3f5b43072eec2877efc1a6159a665fed65"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cd95b62f08093471065ae91fac25814359eab4ee191ec34ec57ae948049e4538"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "d467668cd3627a73b805d928b5ebff2f2f7db857"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "91a129800d610f39c0635bf94666d670cfebdb3db9862a8563ce3ca98c40e9fe"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "4949025cec3c67421558a91c352d66c7eb8c38d8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "58322f469cee20b03e6e7d09cb4a808d66804250f2c88d415aae1a9eb97263b4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "8f6ac11283232cad7d1f27ebb7cc06a7ce9f21fd"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ff1e8384e0c50a565300e103995b7a2584178a3c0d1a72273315593ea056b00d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ae03266118382f337937f72da4cc68b270f936c7"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "7836bb288c73ac7601101155b52890d05dd72dc2ee56a4f53915a0a3f74308bf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "1f1a6d2424852aa0c5a0bb7905036bbc4adcc491"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5e191a28d9b33d84ba9c66f95e044b76b2616d1825dfd8504dbf7cc8ec159edb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "fa0a52e2b467645b3e87b3f1a325a007b3df3783"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d97aa198b59706695cad89b23dc185cecba070213d3569e53911d93f61115392"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "624d6745c8636440aab9392f986904526984836a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d0c8a8f4990d2706fe9d5c6e8bbecf2651959d139d58cb3b1a824ac473845366"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "babab4ab1bccf7672cfebf92731b9cc4c87c5ffe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6de134061b457a7931863235b9fb1b9582c88d8d08eecd3e50dfa0d456e1a563"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9f4b7b02e586f0dede39f78097aa0a694fa19df4"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "85d5f07731a5b014f1b9035fa045ad7afbffd474549cc117088b1fcf8fbb2883"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0549224fe7802c5721fda41cea7489ef52d8f71d"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d79849359e47a9a5acf014b3135b3eda7114161b23175c8ab3cd8ca00b60b861"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9266b43eea4f1e29629dea61c65fcc50ba29106e"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "351ede2a7c23333aea711d05c75cf8476ce81227f6839fef17820fff19056c92"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "8da7299f0a9778f16e61ebc301d50d0e75011417"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "822722c743b8cb9641e56414bcd538a1cc57927e227430276a1f376638c512c4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "9d7c145c183adb9f2f4df30a7531e4ef1c95cdc3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "cfc6c5e91310b2533bf90f5af6b5ab87f53c1bee7a76d40f1b08e2b02809d82c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6246156d2c4d2a868af02f0470a087e2a4cba491"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7dc7b1a07254c784abc5cdca07a4deb457ef641d60e36b47773ccddf47fa8dcf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cdd51d18f765a9644cddae100b4eb85eaa0d6cea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "be80840458f546b9ae37d5045299604331d741980da5b1c70f6cc79bf7389270"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c90837fd87663e540be83fd7e863b3032c229aab"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "39f609531fce0b831e2c1a967bcc6157b8fa5ab70cd3220a10843e0731cecae1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "79252f8ae1550dd5b6e145843875151cfa12e01e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "df2cb2ec67829e5f07648c113e9a96db82bc905aad9764f1c9223ac4e2d174f2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "dcc5463d77c6f4ffa2584a994a88ee29bd0767ba"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "156811423436eea1a3afec8b43464ca38c32305fe0826d77c0956588be461907"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "36961deffaaf53b530aeb583bb867983ca8f4df2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "a352e396381a1260a2441a3b89eccad941a5ccff5ee34174f34cf2d0cfe1a4ec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6a6f0379625e1a64090baa44f98bd4d96a64fc64"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "85df068bbc783086b8b7e68f482c49732c08ca22362a17ed0455c4ccf7461223"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f64eae7c5d30b96d69af3c1b8df718f67047d0f8"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "57d1344b6bced2162444224721928242d1e1db810428ca84b67b5f8612e0025b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7e4f665c4b9a76835031a205a605e89abd98917c"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "3cf2f02f701eee77c394740f72c8f0adad356a88accb0a1650f49cd6db6fbd2c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0316fdc27ab249eccb1f8e1c2fc3e111e8477070"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "85196dc27d0c44ca7532ca470c7ff77607ffee3809d2462d5dd4eae310991694"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.2.1+4/MUMPS_seq.v5.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
