[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "d9996b5313e016b4476dc30bcb4dfcaafa754752"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "298f9993817546a40801b955bcf4ca7ce10f97c6341b8174a08a64bafb96dd2c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "3caa0cd81daea1b6daba3f360a2c285efa1a7955"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "658abe822a9a5661ca4536f536b018591bd1cd2ea92f82441ba4634af088174b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2e9af013bd1a293e03e9fbb87a1d52839fbf028e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "04f33008d5d36d3665dce360f4b6c8cbe10f50f55f001c60ee47debeadfa72be"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "552ca67285fcec644fa2d1df846405dea397d782"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b0e6e967341eeb95d0dd484254c9187034b79cdbf48320422fa4fa05df4c70f3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "75e55d74c0a1f155c96ef9ae94eeb4eb02408343"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "94b193020798383666c39191c64e8341107f6c93103e248f2af8e7f60792ed18"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "3a5630f01c095db227207ffecdda29e749a192ef"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "416f29b1b25216007d06be9744ab044af82bfcef8d6653a392530c6a360da148"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "023c9d3098a1a3629a2101843e168b8cd737599a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "b80df40c1a89b827e6eb387db9ab0df4980d4ddaba7c356ceb0cfa48d1858f77"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d71532cf28d2b3d9e2cff7a649a1a9a1a7d3f9a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a9c65f23771c5c0472efa0d12fc7d7b0c1ed4f32e448a7b9b03183d33d4daa2a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f523f93992ec4a258d19cb3c55a42e9ca9190a40"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "29fde54840c8f311de9063d0d06daf1a0b46618422f57cfaf378cd27fa1d1ea3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b16778acc3aaf3c1d89b18ea50450754a8d2f480"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f94b72c013041aaf5947b5ae14b52c7ec72ae42ec4c213f1e7f1f34c0092bc44"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "281aab9b90871fd32bac9cccc78243545693fd3d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2dab3e2c578e3795e58fef6bd7acd7306ac8ba614082f9dd20d4e1cf300211cd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57323f01554433c962124ac3183cc629230e2215"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c3ba725b5a0c329dfbf7f7c0b2631cb72ed3bbbe972672b3b936eaa24368bf70"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "7b7887ed62793c195a28d89ce8c89ce661999903"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "71075e973d80591a5320fc3c34bed1d33c300701530d889dd2d6d5c069cb714f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "efb8b73cb6184fdbbf17306b65fde0f488b96a92"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dfd977cb267d90036d3b60c0cdf06303cb4d658d4a05fd3c2c2b26b4ce4907b0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "204fb075f4fee96454601b4d4085667de47f913c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a5538a53fe19b7c66c8470f7d0a4e1f4bd858726a30769ffd0887d74186801bb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "abc75164771f2c1ef906f409931bb935f0f767ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4e1a5ab60500f4d60bc5ef9e0a531e06bf0af04270877111b3a46b47673b7def"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "cfa1ca081547145c4796dab58753d67d3e1e0776"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "78bb95357e91e3f4a184bb58bbfaebc587e3e4564361fec792a1b5321c215e1d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "40f2ddff5ef8e9ca0d6e51564348c5243fa91356"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "55087c1a1fb7a055918f75ef8fbc030441aa03d2d095c7d85c2510a7a1cd0d29"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "84f5c5692e49484cf5f82e75642570229be561ae"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "6cb8621b2cdd819a60f70d1be3effe346f6b11c921404c82742407727c0e268b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "905dca2b57bca9c1ef41a9dcb34b47e11fcf0b14"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "72c2f2d4519ab782a88e4056c73446d28b3008ee00d529cdff8560dfcde7469b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "42f4e4d0a443a937523f314624eb4257fb10e884"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "f1880281f53763526d64c8f98b87c21f240a1af6c35f2109da1eb6d14ec88b5e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "0f92316ffa60c6d48f634973a02886297790b9e9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "41487869f3fede5d9faba795fff591aff850be19c9d06b8787caae02f7af98fa"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "0b57a45284a5fef68855240e12bdfb747800e868"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2388200257fb56ab4eaf0ad0b4bab253758e8d5ecdde78a4842d2ad9528c6aa1"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "ab805769ff021db52c0aa66302791cf6dde82ecc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "986a7bb94df7c83318a98c92df7a7e3676e3e37601d4b1747a801c1d8a5fabd7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5f3d8459dc57efd3e1e95e3a72b7c69e3252067d"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "a7d53296017ad7c903ce2895b5c34bce5c826595b2433b4be70847a47d2ac37c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "2bad19484821fb01746784b171b624dfaf5f1d79"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1816df88cda1dac3feb70eb217b9c2e1d9128649255ce34fee64935afba1d63c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "4948df7d111aee26337b993dec68ab521f739cd8"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "d36480e55cacdfe123761fdfd2b7971e876bb028efb443fbcb097075b320acbb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "c62776fab74d3376a44d2b3e0f5bd4ca4ea5a28d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "24dcebd25204ce2171dc82bf8534408ab89f584bc8c0f07da46318ed37319fec"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ad5ff2a3f16cc91386d488d897a8d9a36cb5e849"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "607185e2da64124798e148d959e898a74603a92365585a2ff57c1fa7aa8f550e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7db8aa20345493267b770e78ac792cea09dfd325"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7b536247bdeb24e65fc93e558bdaf0beb08cd2f00c122970b80ae2a56c53f856"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d9c60ff11c2c565d29e63e61902d39f03ce375ef"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6774901ecdf7a346fbae81b8183d8dfeb9285e737b6150dd18d53a185f546893"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6556ac2e09c12fcbb4b9e3b29b1fede4e10d6e77"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "26dac2d2d7fd33b77358b2bdaf8d5d6e7807f6037f26cbce6df85dc0223bdec5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "91737ab67d4662cd05d7baa3b223471977fe6778"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "4c9968538e8a017f270401069902218df011d9de15e964b93011560dd5d89e94"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "18fbfce8ce2e29e900ae703028fb7415d3130867"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "643ac3b3bacea9754da95572bb1d8cace3fc728ee0d2a13c985f088aed182c33"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ed123bf44464c0692fb23a0f36965cc89b31dea2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "457874447064551ac1f1221b1167ae25305310cf16a45f4844c836e548f14b8d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b47c4071df63424609817a3eeb12b3afff8185f8"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "644a7d54da1f456ac66a178b3939b0571faf19f01e81c368feb7fc647cdee56c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d1e2dd2dfa70c11cb0653e5cae6cbc5ee19d70a4"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "d0c3737f524d64c9009ebcd5abb46762dfc9d298711510ec93bac40334bae184"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "1848d9d997849f238047001bce66eb721362ab59"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "c93804e1b829338430a3f1fba30b9f1579f3b075f00f480f55e4c23f47ecce94"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cc99e7112714c4283bc53b8bf395d4468d8b9e41"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "ff0f217ccb3e39875b2c98ecf82e0d7d9f7ff1830f3e40ef7b14a26bd9c08ae5"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.3.5+0/MUMPS_seq.v5.3.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
