[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "106559e21cdbf3e22363374dcbee80eb6c692d89"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "7d4c8319afdcac68bcb70612cb29f487025a0cab5541a0b8003cc7f91947fa63"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "9c5e5c8e7c4e1083b59d921a08f9fdecbd0db62b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "edeec71b49775b3f48ebdbf955edb9429b078959c63bb665ef2416c049a32199"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "e162aa70a7d948380bc988d49100728ce20b67ca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f212803b067218e85132222bc51a530c45984cd8ce8f1b00b96e04f19d1be083"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "1033cfec2a187c6eb1f0d584e3f3359bafff6ca6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8109e80c5b6caaa4ad097fea81e82a9e4fe2641a0f6bc24bfe2286242e3fd82e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "74cdac18f873a0a96a786ee51bc3e25a7adfde26"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9ad982b9f5a859ffd2921afb2854f64d1cafd8958335d7fa0772f5c858a0cafb"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "9983133e02876669ee839a846e903e5aefb08672"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d9ac1ef7bf0fbf118fc68ed3e7085dd8418802979c00f319733f2a2944b9146b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "12ea6a8e97804cc101938ebdcf8fa5a8e473faa3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6a10f37afb9fa2c0e7f696566603479a9e7033d5248969fb3adb647a3e1a83dd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.aarch64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d843b8d08b845579bcc45d8e1dff3ab67b9afc1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d66daf6f5aa0fc14edff0079efca532b8405f3b51acb675b1e63b4162ef26cdd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e90c2e4b499293fcff255dbd7ee25842d258b3a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "dc7cf20ec7a217a5a5d6474152fd55d2c48d7f25d4e653e77740b28524f352ee"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7b2a84b13a733c057c3703cf0c8bfabf07e88cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "961dfc959f0b25100565d2b364015e2dadb40b20c66693712a49f31a605ea2dc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "72d9e5463465b96435916c4c6ff85fce8405ca60"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3de15e11973d5fc102bf19c7f939ba3787b46ac68ddaa4e2af3f07d59d2ebe17"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56203015aa980b9f6a0bd3cf972be5a819f1664f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fafaad43ad10f17f28bf976c18d8e1935c92e2fdb293667c60aa150dbef17df2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b51e6f35979e9e92d433c83f8c60efab7b40ca8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "55828286a256afa42eab0811dc5de2b3aacbedaedb476d13e60772fdd782781f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72151f665b778afd759cbf617147ebfe96a207a9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "ce57c96a672915e70f81b2cd572b8daa48c4d9693ff9a5c2724dccb38841c6e4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fdda1b735f44a40395e8b18ebe1ae6b3d14eb5c8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "eebb7068bf4eba1ca2bac18a2eb1a55f0432ef08a1872ea1f15a1a6b91c2e04f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8173d68a3639e43e5ecf9774c2f8b4df7dcc7ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "1aa4228458b6751561f67c6e402363aa1216f7955d9e018366f53089d5190cdf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a67340de4ee8f0ff05e71d1cf9b9a28415e0fdd5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7b8dd836624a1080013b11b6e6da0d7522ca0206ba29b44a5967ed3b4758e23e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9717fb58f30f589970d5db1d835bb08996eac881"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "8e24607d7c15bcf94cb10c2d511ca0a06895140ce7ee707354881d310d497acc"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8896527438ae551aa46e3af38e4b3fd606a7177b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "3651d7a56e7988b4c2ee1a9f7adbfb7f436877babbcca5ff65625230afcf3a81"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "38aee6574e593e01265c9a2bcad8cbcc42fc7df8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d90b3e6a065cf0d34c5bc408ac62bafae53bd17914f6ad7f58939620c4ed3c70"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "522d1f161768bd2853c6816c375c9cf0f8d9f238"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "7f27163ec679559a2b4e699bf5774562fdf81b6ba1c0d205ddc3f396bad83a35"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "837200567a90ced6f963ac2665da85eb1c7eb37a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "86e93030c7c791eee4c2dfbf2789b7709deabaf65ac9a1b4745cfa2b988666b2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "bfe9da5e8854a4524320bab83ae5dfe9608d22d7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "d89cc260a2fae40c671d475ec8a66995145a919817a7683dfac14cc5af996e00"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "5ce5fca7fe56d9cd4af675d2e37bbb0bf9bc82b5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6e4fbe6b10f08d119178a3d1df96ab13a3bcad2e2c0c41fcae80b8c1822f7f62"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "460ac248a7c0971d1f073e9c0d99ec393ef7205a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "85d4d7f5fc70f9de7d2e966e87cb10f6fd955b4b631af90a3bb851ad1bbd8c5b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "2d0e28058a4bba6ff52144a4846ab05cd8c897d4"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5f2a83fe9fb8a70aead0b95fab47add378c5e798ce392bfccb1444488aede637"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "edb0d58b5a84fbb73942b48fbf9923b69402d987"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "47dc412d52fa51f934d984ad06f86ccd34b10213ef7eca58f951887dc327cf90"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "i686"
git-tree-sha1 = "ee28625ffe0d7c50a3aa2d63508d559d0323a418"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "484843f09bf3584173200117fa9666d0c336b03b2849fb84d43357946adff2ef"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.i686-w64-mingw32-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "56356c407b588134558a058920104f2041580695"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "6dca32afbbd1c1d129ebd1445b92f306a748202cd59a490075e9d8be24323595"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "74d16871f3269b52980c8a7bf2d5657eb0aebf4d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "e77b7e12e51818adeb2ade84c95babbe291df28b66e9e7d5e9666262c8adddb0"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "powerpc64le"
git-tree-sha1 = "ae660ca48736d10cbcdd074616e879987b7390f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "f15002ad911448f2950edefb729e4be85fde054b4c5746a33d242b5f9a2bd91d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "56e83f89625368714052be6d3d95106399d665d7"
libgfortran_version = "3.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "65dbd8a16ff8ef296c369e746d888b684f707e3884b5697adaf4307b239a8363"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "96c37812286729fdb39d50fa0fa0a138549c4e68"
libgfortran_version = "4.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "a39c0c97c935c5841ddfdffc24ad572179bcc4534d9eb5fa05ac2dda64fb5c6c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6375bdaa216a15d2c704858449655c1c6d31be92"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "70560055330ae74d3c2611e05d1fb172d2668fc84160cc21128d08acf2c90435"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "d7486ff8181d808ade4d03d650c8f9d0014ea277"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "39e6756ecfa4ce62572cb9393f335c3433a7ac8d0824e6266c8debf1b409c60b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "464b771a26e87c8ddd3281a3201624313ab0992d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "fd63e66a2190cbc38dad6d14faaa7d861320c21e2261320b85538120095d8e41"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "b8060737aa86a09bc6d23d1a6c8c7c3246428d41"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "9970a45ccf8e343d2ee8e820864bcdb6516b376e8b7f3bd45f1eef2fe8909e74"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "e3eb3476052f66eab36b8b64fb7619c27302733e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "870908bda4af32d95bc11820d278076055a6d83127a7dd4afdcd723d5cda93e2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-musl-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "46d9b41c0f13e007712442b4c3ef49cedf7e063d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a888e0c4cb27f46f2a4fff4b1ff4143c29aa0d30f084e380a4d283f3b87615dd"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-musl-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5f066b3b6be395d0ff2a3150a99efaa58635e109"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "da7a5b4f94963b19364fc63e789d13bfa8f1e656cacdfb734abd94af46ddeee2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-linux-musl-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "694a19cad18d9abdc8064bae8664e8a9e443c284"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "b5fcda52f6350af196118796c529f08a1589c96cad36d2329192ebac7209ce9a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f0871fd4d33f575601f96fc7c4977f8102f33b6c"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "bbd4c71885e9e7af5681740141e97b2242ebbad8e0b406dce9ee2bf0964ec89a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "6136afed11380f1b951f2e4e21fa34a26e7f96ec"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MUMPS_seq.download]]
    sha256 = "db5f69675a375f09fa8a746cce70ee31b0cd7469fc630155c785549a90429e17"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "a9bee940d935697654deb57a951825a4d9db4223"
libgfortran_version = "3.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "0c6444a712441ae060fa830871718b817887fd0106a00f76efcb7be9ce0bb061"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "cd215e2ae4791b6c53887936fbfe36d728b99075"
libgfortran_version = "4.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "098041b23e58735c05e1dad0fe14035d832494a7849f13486eef385632628df7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "bf4a9794724af4451268ed22a688fc4328bc1400"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "8a00caad6787dab244ea685aaba1b7cc3c732bc62c25c4e3e50c97843a74721b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v500.600.201+0/MUMPS_seq.v500.600.201.x86_64-w64-mingw32-libgfortran5.tar.gz"
